const {JSDOM}=require(process.env.FORJA_JSDOM||'/tmp/forja-ui-test/node_modules/jsdom');const {readFileSync}=require('node:fs');const path=require('node:path');const assert=require('node:assert/strict');const {randomUUID}=require('node:crypto');
const root=path.resolve(__dirname,'../audio-diagnosis/forja-v17/server');const dom=new JSDOM(readFileSync(path.join(root,'insights.html'),'utf8'),{url:'https://forja.test',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;w.IntersectionObserver=class{observe(){}disconnect(){}};w.HTMLElement.prototype.scrollIntoView=()=>{};w.crypto.randomUUID=randomUUID;w.URL.revokeObjectURL=()=>{};w.URL.createObjectURL=()=>"blob:fixture";w.AbortController=AbortController;w.Response=Response;
const id=randomUUID(),command=randomUUID(),now=Date.now();let devices=[{id,name:'<img src=x onerror=alert(1)>',enabled:true,seen_at:now,online:true,status:'ready',command:null,position:null}];let defer=null;const calls=[];
w.fetch=async(url,options={})=>{calls.push({url,options});if(url.endsWith('/recovery/devices')){if(defer)return new Promise(r=>{defer.resolve=r});return Response.json({devices});}if(url.endsWith('/state'))return Response.json({me:{id:'alice',name:'Alice',code:randomUUID(),session:null,location:null,places:[],history:[],explored:[]},friends:[],incoming:[],groups:[]});return Response.json({ok:true});};
const layers=[];w.L={map:()=>({setView(){return this},remove(){},invalidateSize(){},flyTo(){},getCenter(){return{lat:45,lng:24}}}),tileLayer:()=>({addTo(){}}),layerGroup:()=>({items:[],addTo(){layers.push(this);return this},clearLayers(){this.items=[]},remove(){}}),divIcon:o=>o,marker:(point,options)=>({addTo(layer){layer.items.push({point,options});return this},bindPopup(){return this},on(){return this}}),circle:(point,options)=>({addTo(layer){layer.items.push({point,options});return this}})};
w.eval(['insights-client.js.txt','files-preview.js.txt','files-client.js.txt','cleanup-client.js.txt','organizer-client.js.txt','social-client.js.txt','recovery-client.js.txt'].map(f=>readFileSync(path.join(root,f),'utf8')).join('\n')+'\nwindow.h={login:()=>{auth={token:"fixture",expires:Date.now()+3600000,controller:new AbortController()};},page,refreshRecovery,renderRecovery,recoveryUI,recoveryMarkers,logout};');
const tick=()=>new Promise(r=>setTimeout(r,10));const box=()=>w.document.getElementById('recovery-devices');const click=text=>{const b=[...box().querySelectorAll('button')].find(x=>x.textContent===text);assert(b,text);b.click();};let checks=0;
(async()=>{
 w.h.login();w.h.page('social');await tick();assert(box().textContent.includes('<img'));assert.equal(box().querySelectorAll('img').length,0);assert(box().textContent.includes('Nu există încă'));checks++;
 click('Localizează telefonul');await tick();const start=calls.find(c=>c.url.endsWith('/command')&&c.options.method==='POST');assert(start);const body=JSON.parse(start.options.body);assert.equal(body.minutes,15);assert.match(body.id,/^[a-f0-9-]{36}$/);assert(!start.options.body.includes('alice'));checks++;
 devices[0].command={id:command,phase:'queued',start_before:now+300000,until:now+900000};await w.h.refreshRecovery();assert(box().textContent.includes('încă nu avem confirmarea'));assert(!box().textContent.includes('Telefonul a confirmat'));checks++;
 devices[0].command.phase='active';devices[0].position={lat:45.1,lon:24.3,accuracy:28,at:now,battery:70};await w.h.refreshRecovery();assert(box().textContent.includes('±28 m'));assert(box().textContent.includes('Poziție recentă'));assert.equal(w.h.recoveryUI.layer.items.length,2);checks++;
 devices[0].position.at=Date.now()-120001;await w.h.refreshRecovery();assert(box().textContent.includes('nu este confirmată acum'));assert(w.h.recoveryUI.layer.items[0].options.icon.html.className.includes('recovery-stale'));checks++;
 click('Oprește căutarea');await tick();assert(calls.some(c=>c.url.endsWith('/command?id='+command)&&c.options.method==='DELETE'));checks++;
 devices[0].position.at=Date.now()-86400001;await w.h.refreshRecovery();assert.equal(w.h.recoveryUI.layer.items.length,0);assert(!box().textContent.includes('45.10000'));checks++;
 devices[0].command=null;devices[0].status='location_off';await w.h.refreshRecovery();assert(box().textContent.includes('Site-ul nu poate porni GPS-ul'));click('Dezactivează găsirea acestui telefon');await tick();assert(calls.some(c=>c.url.endsWith('/grant')&&c.options.method==='DELETE'));checks++;
 defer={};const waiting=w.h.refreshRecovery();await tick();w.h.logout();defer.resolve(Response.json({devices}));await waiting;assert.equal(w.h.recoveryUI.data,null);assert.equal(box().childNodes.length,0);assert.equal(w.h.recoveryUI.layer,null);checks++;
 console.log(JSON.stringify({recovery_dom_checks:checks,live_browser:false}));dom.window.close();
})().catch(e=>{console.error(e);dom.window.close();process.exitCode=1;});
