import test from 'node:test';
import assert from 'node:assert/strict';
import { InsightsAccount } from './insights-store.mjs';
import { buildEvidence, validateRecommendations, loadJournals, internalRequest } from './insights-ai.mjs';
import { randomUUID } from 'node:crypto';
class MemoryStorage {
  values=new Map(); alarm=null;
  async get(k){return structuredClone(this.values.get(k));}
  async put(k,v){if(typeof k==='object'){for(const [a,b]of Object.entries(k))this.values.set(a,structuredClone(b));}else this.values.set(k,structuredClone(v));}
  async list({prefix}){return new Map([...this.values].filter(([k])=>k.startsWith(prefix)).map(([k,v])=>[k,structuredClone(v)]));}
  async delete(k){for(const key of Array.isArray(k)?k:[k])this.values.delete(key);}
  async setAlarm(v){this.alarm=v;} async deleteAlarm(){this.alarm=null;}
}
class Bucket {
  files=new Map();
  async put(k,v){this.files.set(k,new Uint8Array(v));}
  async get(k){return this.files.has(k)?{body:this.files.get(k)}:null;}
  async list({prefix}){return {objects:[...this.files.keys()].filter(k=>k.startsWith(prefix)).map(key=>({key})),truncated:false};}
  async delete(keys){for(const key of Array.isArray(keys)?keys:[keys])this.files.delete(key);}
}
function fixture(bucket=new Bucket()){
  const storage=new MemoryStorage(); let queue=Promise.resolve();
  const ctx={storage,blockConcurrencyWhile(fn){const next=queue.then(fn);queue=next.catch(()=>{});return next;}};
  const object=new InsightsAccount(ctx,{RECORDS:bucket});
  const call=(path,method='GET',data,uid='userA',headers={})=>object.fetch(new Request('https://test'+path,{method,headers:{'x-forja-owner':uid,'content-type':'application/json',...headers},...(data===undefined?{}:{body:data instanceof Uint8Array?data:JSON.stringify(data)})}));
  return {call,storage,bucket,object};
}
const consent=(...ks)=>Object.fromEntries(['location','app_usage','files','photos','audio'].map(k=>[k,ks.includes(k)]));
async function session(f,...ks){const id=randomUUID();assert.equal((await f.call('/v2/sessions','POST',{session_id:id,consent:consent(...ks)})).status,201);return id;}
function phone(){return {locations:[{at:1000,latitude:44.4,longitude:26.1,accuracy_m:8,segment:1}],visits:[{first_seen:1000,last_seen:1000,latitude:44.4,longitude:26.1,observed_ms:0,samples:1}]};}
function wav(){const b=Buffer.alloc(32044);b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(16000,24);b.writeUInt32LE(32000,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(b.length-44,40);return b;}
test('online metrics round trip, receipts, and unknown fields rejected',async()=>{const f=fixture(),id=await session(f,'location');assert.equal((await f.call('/v2/sessions/'+id+'/data','POST',{...phone(),email:'private'})).status,400);const r=await f.call('/v2/sessions/'+id+'/data','POST',phone());assert.equal(r.status,201);const receipt=await r.json();assert.equal(receipt.bytes,Buffer.byteLength(JSON.stringify(phone())));assert.match(receipt.sha256,/^[a-f0-9]{64}$/);assert.deepEqual(await(await f.call('/v2/sessions/'+id+'/data')).json(),phone());});
test('concurrent duplicate uploads produce exactly one receipt and one stored item',async()=>{const f=fixture(),id=await session(f,'files');const upload=()=>f.call('/v2/sessions/'+id+'/items?kind=file&sequence=0','POST',new Uint8Array([1,2,3]));assert.deepEqual((await Promise.all([upload(),upload()])).map(r=>r.status).sort(),[201,409]);assert.equal(f.bucket.files.size,1);});
test('account namespaces isolate an identical client session ID',async()=>{const bucket=new Bucket(),a=fixture(bucket),b=fixture(bucket),id=randomUUID();for(const[f,uid]of[[a,'userA'],[b,'userB']])assert.equal((await f.call('/v2/sessions','POST',{session_id:id,consent:consent('files')},uid)).status,201);const r=await a.call('/v2/sessions/'+id+'/items?kind=file&sequence=0','POST',new Uint8Array([7]));const item=await r.json();assert.equal((await b.call('/v2/sessions/'+id+'/items/'+item.item_id,'GET',undefined,'userB')).status,404);assert.equal((await a.call('/v2/sessions','GET',undefined,'userB')).status,403);});
test('selected binary bytes and session deletion including orphan cleanup',async()=>{const f=fixture(),id=await session(f,'photos');const bytes=new Uint8Array([1,2,3,0,255]);const r=await f.call('/v2/sessions/'+id+'/items?kind=photo&sequence=0','POST',bytes);const item=await r.json();const download=await f.call('/v2/sessions/'+id+'/items/'+item.item_id);assert.deepEqual(new Uint8Array(await download.arrayBuffer()),bytes);assert.equal(download.headers.get('content-type'),'application/octet-stream');const record=await f.storage.get('session:'+id);await f.bucket.put(record.prefix+'orphan',bytes);assert.equal((await f.call('/v2/sessions/'+id,'DELETE')).status,200);assert.equal(f.bucket.files.size,0);});
test('consent, coordinates, selected-item and size bounds',async()=>{const f=fixture(),id=await session(f,'files');assert.equal((await f.call('/v2/sessions/'+id+'/data','POST',phone())).status,400);assert.equal((await f.call('/v2/sessions/'+id+'/items?kind=photo&sequence=0','POST',new Uint8Array([1]))).status,400);assert.equal((await f.call('/v2/sessions/'+id+'/items?kind=file&sequence=5','POST',new Uint8Array([1]))).status,400);assert.equal((await f.call('/v2/sessions/'+id+'/items?kind=file&sequence=0','POST',new Uint8Array(5*1024*1024+1))).status,413);const p=phone();p.locations[0].latitude=120;const loc=await session(f,'location');assert.equal((await f.call('/v2/sessions/'+loc+'/data','POST',p)).status,400);});
test('valid audio only and upload window enforced',async()=>{const f=fixture(),id=await session(f,'audio');assert.equal((await f.call('/v2/sessions/'+id+'/items?kind=audio&sequence=0','POST',new Uint8Array([1,2]))).status,400);assert.equal((await f.call('/v2/sessions/'+id+'/items?kind=audio&sequence=0','POST',wav())).status,201);const record=await f.storage.get('session:'+id);record.created_at-=181000;await f.storage.put('session:'+id,record);assert.equal((await f.call('/v2/sessions/'+id+'/items?kind=audio&sequence=1','POST',wav())).status,410);});
test('expired sessions are inaccessible and removed with their binaries',async()=>{const f=fixture(),id=await session(f,'files');await f.call('/v2/sessions/'+id+'/items?kind=file&sequence=0','POST',new Uint8Array([1]));const record=await f.storage.get('session:'+id);record.expires_at=Date.now()-1;await f.storage.put('session:'+id,record);assert.equal((await f.call('/v2/sessions/'+id)).status,404);assert.equal(f.bucket.files.size,0);assert.equal(f.storage.alarm,null);});
test('observations need a real owned item; writes and AI budget are bounded',async()=>{const f=fixture(),id=await session(f,'files');assert.equal((await f.call('/v2/sessions/'+id+'/observation','POST',{item_id:randomUUID(),text:'invented',model:'test'})).status,400);assert.equal((await f.call('/internal/ai-budget','POST',{})).status,200);assert.equal((await f.call('/internal/ai-budget','POST',{})).status,429);});
const journals=()=>({sleep:{records:[],error:null},activities:{records:[],error:null},meals:{records:[],error:null}});
test('no recommendations are supported by a completely empty account',()=>assert.deepEqual(buildEvidence(journals(),[]),[]));
test('evidence omits exact coordinates and labels location meaning as unknown',()=>{const j=journals();j.sleep.records=[{startAt:1000,endAt:3601000}];const data=phone();const e=buildEvidence(j,[{session_id:randomUUID(),data:{bytes:1},metrics:data,observations:[]}]);const text=JSON.stringify(e);assert.ok(!text.includes('44.4'));assert.ok(!text.includes('26.1'));assert.match(text,/Nu știm/);assert.match(text,/NU demonstrează/);});
test('AI cannot cite invented evidence or inject actionable HTML/URLs fields',()=>{const evidence=[{id:'sleep-summary'}];const r={category:'sleep',title:'O seară liniștită',why:'Un indiciu',next_step:'Verifică rutina.',confidence:'low',evidence_ids:['sleep-summary'],url:'javascript:alert(1)'};assert.equal(validateRecommendations({recommendations:[r]},evidence)[0].url,undefined);assert.throws(()=>validateRecommendations({recommendations:[{...r,evidence_ids:['invented']}]},evidence));assert.throws(()=>validateRecommendations({recommendations:[{...r,confidence:'certain'}]},evidence));});
test('Firestore queries are owner-scoped and one failed journal does not hide others',async()=>{const calls=[];const out=await loadJournals('testUid','synthetic-token',async(url,opts)=>{calls.push([url,opts]);const k=JSON.parse(opts.body).structuredQuery.from[0].collectionId;if(k==='sleep')throw Error('offline');if(k==='meals')return Response.json({error:'blocked'},{status:403});return Response.json([{document:{name:'projects/x/users/testUid/activities/a1',fields:{durationS:{integerValue:'120'},type:{stringValue:'walk'}}}}]);},1000000000);assert.equal(out.activities.records[0].durationS,120);assert.ok(out.sleep.error);assert.equal(out.meals.error,'Firestore HTTP 403');assert.ok(calls.every(([u])=>u.includes('/users/testUid:runQuery')));});
test('internal requests set owner independently of arbitrary paths',()=>{const r=internalRequest('verifiedUid','/v2/sessions');assert.equal(r.headers.get('x-forja-owner'),'verifiedUid');assert.equal(new URL(r.url).host,'internal');});
