import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {InsightsAccount} from './insights-store.mjs';import {selection,runLimit} from './organizer-selection.mjs';import {organizeAI,validateOrganization} from './organizer-ai.mjs';import {readJSON} from './insights-store.mjs';import {parsedJSON} from './insights-ai.mjs';
class Storage{values=new Map();async get(k){return structuredClone(this.values.get(k));}async put(k,v){this.values.set(k,structuredClone(v));}async delete(k){for(const key of Array.isArray(k)?k:[k])this.values.delete(key);}async list({prefix='',limit=Infinity,startAfter=''}){return new Map([...this.values].filter(([k])=>k.startsWith(prefix)&&k>startAfter).sort(([a],[b])=>a.localeCompare(b)).slice(0,limit).map(([k,v])=>[k,structuredClone(v)]));}async setAlarm(a){this.alarm=a;}async deleteAlarm(){this.alarm=null;}async transaction(fn){const before=structuredClone(this.values);try{return await fn(this)}catch(e){this.values=before;throw e;}}}
const choice=(v={})=>({photos:true,files:true,photo_count:50,file_count:100,photo_folder:'DCIM/Camera',file_folder:'Educație',from:null,to:null,recursive:true,wifi_only:true,...v});
async function setup(organize=true,protocol=2){const storage=new Storage(),bucket={async delete(){},async list(){return{objects:[]}}};let queue=Promise.resolve();const object=new InsightsAccount({storage,blockConcurrencyWhile(fn){const p=queue.then(fn);queue=p.catch(()=>{});return p;}},{RECORDS:bucket});const call=(path,method='GET',body,owner='ownerA')=>object.fetch(new Request('https://fixture'+path,{method,headers:{'x-forja-owner':owner,'content-type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})}));const device=randomUUID(),grant=randomUUID(),base='/v2/organizer/devices/'+device;const granted={id:grant,enabled:true,photos:true,files:true,label:'Phone',...(protocol>=2?{protocol,organize}:{})};assert.equal((await call('/v2/cleanup/devices/'+device+'/grant','POST',granted)).status,200);const id=randomUUID(),request={id,revision:1,selection:choice()};return {storage,object,call,device,grant,base,granted,id,request,async create(v=request){const response=await call(base+'/request','POST',v);assert.equal(response.status,201,await response.clone().text());return response.json();}};}
async function evidence(f,n=1,source='photos'){const items=Array.from({length:n},()=>({id:randomUUID(),name:'Fișă.jpg',kind:source==='photos'?'photo':'file',source,folder:'DCIM/Camera',destination:'Educație/Fișe',reason:'Conținut educațional',excerpt:'Numărăm merele: 1, 2, 3.',partial:false}));const result=await f.call(`${f.base}/runs/${f.id}/items`,'POST',{grant_id:f.grant,items});assert.equal(result.status,200,await result.clone().text());return items;}
async function received(f,items){for(const i of items)await f.storage.put('cloud-file:'+i.id,{id:i.id,device_id:f.device,kind:i.kind,name:i.name,cleanup_run:f.id,sha256:'a'.repeat(64),bytes:10,received_at:Date.now(),expires_at:Date.now()+86400000,thumbnail:false,media_type:i.kind==='photo'?'image/jpeg':'application/pdf',preview:i.kind==='photo'?'image':'pdf'});}
const approve=(f,items,patch={})=>f.call(`${f.base}/runs/${f.id}/plan`,'POST',{id:randomUUID(),grant_id:f.grant,items:items.map(i=>({id:i.id,destination:i.destination})),confirm:true,...patch});
test('independent counts, all scope, folders and dates validate',()=>{const grant={enabled:true,photos:true,files:true};assert.equal(selection(choice(),grant).file_count,100);assert.equal(runLimit({selection:choice({photo_count:0,file_count:12})}),15012);for(const patch of [{photo_count:-1},{file_count:15001},{photo_folder:'../private'},{file_folder:'a//b'},{photo_folder:'/storage'},{from:9,to:2},{files:false,photos:false}])assert.throws(()=>selection(choice(patch),grant));assert.throws(()=>selection(choice(),{...grant,files:false}));});
test('old clients cannot accept expanded requests',async()=>{const f=await setup(false,1);assert.equal((await f.call(f.base+'/request','POST',f.request)).status,409);});
test('on-demand request works with calendar off and survives unrelated calendar revision',async()=>{const f=await setup(),run=await f.create();const result=await(await f.call('/v2/cleanup/devices/'+f.device+'/claim','POST',{grant_id:f.grant})).json();assert.equal(result.run.id,run.id);assert.equal(result.next_at,null);const d=await f.storage.get('cleanup-device:'+f.device);d.revision++;await f.storage.put('cleanup-device:'+f.device,d);assert.equal((await f.call(`/v2/cleanup/devices/${f.device}/runs/${run.id}`)).status,200);});
test('requests are idempotent, bounded and owner bound',async()=>{const f=await setup();await f.create();assert.equal((await f.call(f.base+'/request','POST',f.request)).status,200);assert.equal((await f.call(f.base+'/request','POST',{...f.request,selection:choice({photo_count:100})})).status,409);assert.equal((await f.call(f.base+'/request','POST',f.request,'ownerB')).status,403);await f.create({...f.request,id:randomUUID()});await f.create({...f.request,id:randomUUID()});assert.equal((await f.call(f.base+'/request','POST',{...f.request,id:randomUUID()})).status,429);});
test('grant retry cannot silently expand move consent',async()=>{const f=await setup(false);assert.equal((await f.call('/v2/cleanup/devices/'+f.device+'/grant','POST',{...f.granted,organize:true})).status,409);});
test('metadata paginates, is idempotent and expires including extracted text',async t=>{const f=await setup();await f.create();const items=await evidence(f,30);await f.call(`${f.base}/runs/${f.id}/items`,'POST',{grant_id:f.grant,items});const page=await(await f.call(`${f.base}/runs/${f.id}/items`)).json();assert.equal(page.items.length,25);assert.equal(page.total,30);const next=await(await f.call(`${f.base}/runs/${f.id}/items?after=${page.next_cursor}`)).json();assert.equal(next.items.length,5);assert.equal(next.next_cursor,null);const expiry=(await f.storage.get('cleanup-run:'+f.id)).expires_at;t.mock.method(Date,'now',()=>expiry+1);await f.object.alarm();assert.equal((await f.storage.list({prefix:'organizer-item:'})).size,0);assert.equal(await f.storage.get('organizer-count:'+f.id),undefined);});
test('duplicate metadata ids do not bypass selection limits',async()=>{const f=await setup();await f.create();const [i]=await evidence(f);assert.equal((await f.call(`${f.base}/runs/${f.id}/items`,'POST',{grant_id:f.grant,items:[i,i]})).status,400);});
test('no move without explicit phone opt-in and a confirmed uploaded copy',async()=>{const f=await setup();await f.create();const items=await evidence(f);assert.equal((await approve(f,items)).status,409);await received(f,items);const granted=await f.storage.get('cleanup-device:'+f.device);granted.grant.organize=false;await f.storage.put('cleanup-device:'+f.device,granted);assert.equal((await approve(f,items)).status,403);});
test('plans reject wrong run, path traversal and mixed sources',async()=>{const f=await setup();await f.create();const photos=await evidence(f),files=await evidence(f,1,'files');await received(f,[...photos,...files]);assert.equal((await approve(f,[...photos,...files])).status,400);assert.equal((await approve(f,[{...photos[0],destination:'../Documents'}])).status,400);const copy=await f.storage.get('cloud-file:'+photos[0].id);copy.cleanup_run=randomUUID();await f.storage.put('cloud-file:'+copy.id,copy);assert.equal((await approve(f,photos)).status,409);});
test('approved plan is idempotent and includes hashes for original verification',async()=>{const f=await setup();await f.create();const items=await evidence(f);await received(f,items);const id=randomUUID(),first=await approve(f,items,{id});assert.equal(first.status,201);const p=await first.json();assert.equal(p.items[0].sha256,'a'.repeat(64));assert.equal((await approve(f,items,{id})).status,200);assert.equal((await approve(f,items)).status,409);});
test('cancelled plans cannot be acquired for mutation; applying plans cannot be cancelled',async()=>{const f=await setup();await f.create();const items=await evidence(f);await received(f,items);let p=await(await approve(f,items)).json();const body={grant_id:f.grant,state:'applying',moved:0,copied:0,skipped:0,message:'Applying'};assert.equal((await f.call(`${f.base}/plans/${p.id}`,'DELETE')).status,200);assert.equal((await(await f.call(`${f.base}/plans/${p.id}`,'POST',body)).json()).state,'error');p=await(await approve(f,items)).json();assert.equal((await f.call(`${f.base}/plans/${p.id}`,'POST',body)).status,200);assert.equal((await f.call(`${f.base}/plans/${p.id}`,'DELETE')).status,409);});
test('pause, revoke and 24-hour expiry block original changes',async t=>{const f=await setup();await f.create();const items=await evidence(f);await received(f,items);const p=await(await approve(f,items)).json();await f.storage.put('intake',{accepting:false});assert.equal((await f.call(`${f.base}/plans/${p.id}`)).status,423);await f.storage.put('intake',{accepting:true});const d=await f.storage.get('cleanup-device:'+f.device);d.grant.id=randomUUID();await f.storage.put('cleanup-device:'+f.device,d);assert.equal((await f.call(`${f.base}/plans/${p.id}`)).status,404);t.mock.method(Date,'now',()=>p.expires_at+1);await f.object.alarm();assert.equal((await f.storage.list({prefix:'organizer-plan:'})).size,0);});
test('AI rejects invented ids and unsafe destinations',()=>{const id=randomUUID(),draft={id,destination:'Educație/Fișe',reason:'Exerciții de numărare',confidence:'medium'};assert.equal(validateOrganization({items:[draft]},[id]).length,1);for(const patch of [{id:randomUUID()},{destination:'../../private'},{confidence:'certain'}])assert.throws(()=>validateOrganization({items:[{...draft,...patch}]},[id]));assert.throws(()=>validateOrganization({items:[draft,draft]},[id]));});
test('AI reads only selected received content, produces drafts and does not apply',async()=>{const f=await setup();await f.create();const items=await evidence(f,1,'files');await received(f,items);const calls=[],env={AI:{async run(model,input){calls.push({model,input});return{response:{items:items.map(i=>({id:i.id,destination:'Școală/Numere',reason:'Text cu numere',confidence:'medium'}))}};}}};const request=new Request('https://site/insights/api/organize',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({device:f.device,run:f.id,ids:items.map(i=>i.id),consent:true})});const response=await organizeAI(request,env,'ownerA',f.object,readJSON,parsedJSON);assert.equal((await response.json()).applied,false);assert.equal(calls.length,1);assert(calls[0].input.messages[1].content.includes('Numărăm merele'));assert.equal((await f.storage.list({prefix:'organizer-plan:'})).size,0);});

test('on-demand work remains claimable after two hours, until its own expiry',async t=>{const f=await setup();const r=await f.create();t.mock.method(Date,'now',()=>r.at+3*3600000);const result=await(await f.call('/v2/cleanup/devices/'+f.device+'/claim','POST',{grant_id:f.grant})).json();assert.equal(result.run.id,r.id);assert.equal((await f.call(`/v2/cleanup/devices/${f.device}/runs/${r.id}`)).status,200);});

test('manual mode needs v21 capability and remains distinct from local analysis',async()=>{const old=await setup();assert.equal((await old.call(old.base+'/request','POST',{...old.request,selection:choice({mode:'manual'})})).status,409);const f=await setup(true,3);const r=await f.create({...f.request,selection:choice({mode:'manual'})});assert.equal(r.selection.mode,'manual');assert.throws(()=>selection(choice({mode:'online'}),{enabled:true,photos:true,files:true}));});
