import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID,createHash} from 'node:crypto';
import {InsightsAccount} from './insights-store.mjs';
import {organizeJobAI} from './organizer-job-ai.mjs';
import {TTL} from './phone-schema.mjs';

class Storage{
 values=new Map();fail='';
 async get(k){return structuredClone(this.values.get(k));}
 async put(k,v){if(this.fail&&String(k).startsWith(this.fail)){this.fail='';throw Error('injected interruption');}if(typeof k==='object'){for(const [key,value] of Object.entries(k))this.values.set(key,structuredClone(value));}else this.values.set(k,structuredClone(v));}
 async delete(k){const keys=Array.isArray(k)?k:[k];assert(keys.length<=128);for(const key of keys)this.values.delete(key);}
 async list({prefix='',limit=Infinity,startAfter=''}={}){return new Map([...this.values].filter(([k])=>k.startsWith(prefix)&&k>startAfter).sort(([a],[b])=>a<b?-1:1).slice(0,limit).map(([k,v])=>[k,structuredClone(v)]));}
 async transaction(fn){const before=structuredClone(this.values);try{return await fn(this)}catch(e){this.values=before;throw e;}}
 async setAlarm(at){this.alarm=at;}async deleteAlarm(){this.alarm=null;}
}
const hash=b=>createHash('sha256').update(b).digest('hex');
async function fixture(options={}){
 const storage=new Storage(),objects=new Map(),bucket={async put(k,b){objects.set(k,new Uint8Array(b))},async get(k){const b=objects.get(k);return b?{body:b}:null},async delete(k){for(const i of Array.isArray(k)?k:[k])objects.delete(i)},async list(){return {objects:[]}}};
 let serial=Promise.resolve();const account=new InsightsAccount({storage,blockConcurrencyWhile(fn){const next=serial.then(fn);serial=next.catch(()=>{});return next;}},{RECORDS:bucket});
 const call=(path,method='GET',body,owner='alice',headers={})=>account.fetch(new Request('https://fixture'+path,{method,headers:{'x-forja-owner':owner,'content-type':'application/json',...headers},...(body===undefined?{}:{body:body instanceof Uint8Array?body:JSON.stringify(body)})}));
 const device=randomUUID(),grant=randomUUID(),root=`/v2/organizer/devices/${device}/jobs`,id=randomUUID();
 const granted={id:grant,enabled:true,photos:true,files:true,label:'Phone',protocol:4,organize:true,...options.granted};
 assert.equal((await call(`/v2/cleanup/devices/${device}/grant`,'POST',granted)).status,200);
 await call(`/v2/files/settings/${device}`,'POST',{enabled:true,photos:true,files:true});
 const spec={id,grant_id:grant,revision:1,source:'files',scope:{folder:'',recursive:true},destination:'FORJA',mode:'online',auto_apply:true,ai_consent:true,...options.spec};
 const response=await call(root,'POST',spec);assert.equal(response.status,201,await response.clone().text());
 const f={storage,account,call,bucket,objects,device,grant,root,id,path:root+'/'+id,spec,granted};
 f.job=async()=> (await f.call(f.path)).json();
 f.command=async(count=0,action='continue',extra={})=>f.call(f.path+'/command','POST',{request_id:randomUUID(),revision:(await f.job()).revision,action,count,...extra});
 f.items=async(items,extra={})=>f.call(f.path+'/items','POST',{grant_id:grant,items,...extra});
 f.batch=async(items,extra={})=>f.call(f.path+'/batch','POST',{request_id:randomUUID(),grant_id:grant,limit:items?.length||100,...(items?{ids:items.map(i=>i.id)}:{}),...extra});
 f.receipt=async(item,state,extra={})=>f.call(f.path+'/receipts','POST',{grant_id:grant,receipts:[{id:item.id,operation_id:item.operation_id,state,source_sha256:item.sha256,...extra}]});
 f.file=async(item,extra={})=>{
  const bytes=item._bytes??new TextEncoder().encode('Exerciții de matematică pentru școală.'),copy=extra.id||randomUUID();
  const r=await f.call('/v2/files/'+copy,'PUT',bytes,'alice',{'x-device-id':device,'x-file-kind':'file','x-file-name':encodeURIComponent(item.name),'x-file-folder':encodeURIComponent(item.folder),'x-media-type':item.media_type,'x-file-sha256':hash(bytes),'x-organizer-job':id,'x-organizer-item':item.id,'x-original-id':item.original_id,'x-original-version':item.version,...extra.headers});
  return {response:r,id:copy};
 };
 await f.command(options.count??0);return f;
}
function entry(patch={}){const bytes=new TextEncoder().encode('Exerciții de matematică pentru școală.');return {id:randomUUID(),original_id:randomUUID(),version:hash(bytes),sha256:hash(bytes),name:'Fișă.txt',folder:'Documente',media_type:'text/plain',bytes:bytes.length,modified_at:Date.now(),...patch};}
async function selected(f,items=[entry()],extra={}){assert.equal((await f.items(items,extra)).status,200);const r=await f.batch(items);assert.equal(r.status,201,await r.clone().text());for(const i of items)i.operation_id=randomUUID();return items;}
async function ready(f,item){const r=await f.file(item);assert.equal(r.response.status,201,await r.response.clone().text());assert.equal((await f.receipt(item,'ready',{file_id:r.id,destination:'FORJA/Școală'})).status,200);return r.id;}
async function moved(f,item){await ready(f,item);assert.equal((await f.receipt(item,'applying')).status,200);assert.equal((await f.receipt(item,'moved',{target_sha256:item.sha256})).status,200);}

test('v4 is owner and grant bound; creation retry preserves the same durable job',async()=>{const f=await fixture();assert.equal((await f.call(f.root,'POST',f.spec)).status,200);assert.equal((await f.call(f.root,'POST',{...f.spec,destination:'Other'})).status,409);assert.equal((await f.call(f.root,'GET',undefined,'bob')).status,403);assert.equal((await f.call(f.root,'POST',{...f.spec,id:randomUUID(),grant_id:randomUUID()})).status,403);});
test('source ID is a real phone grant, with relative subfolder scope',async()=>{const source=randomUUID();const f=await fixture({granted:{sources:[{id:source,source:'files',label:'Documente',folder:'Primary/Documents'}]},spec:{source_id:source,scope:{folder:'Școală',recursive:false}}});assert.equal((await f.items([entry({folder:'Școală'})])).status,200);assert.equal((await f.items([entry({folder:'Școală/Altele'})])).status,403);assert.equal((await f.call(f.root,'POST',{...f.spec,id:randomUUID(),source_id:randomUUID()})).status,403);});
test('job destination and protected directories never reenter the inventory',async()=>{const f=await fixture({spec:{preferences:{protected_folders:['Private']}}});for(const folder of ['FORJA','FORJA/Școală','../outside','Private/Acte'])assert.notEqual((await f.items([entry({folder})])).status,200);});
test('same bytes in two originals remain two items and two leases',async()=>{const f=await fixture(),items=[entry(),entry()];await selected(f,items);assert.equal((await f.job()).counters.total,2);assert.equal((await f.storage.list({prefix:'org4-lock:'})).size,2);});
test('batch replay returns identical selection without taking more work',async()=>{const f=await fixture(),items=[entry(),entry()];await f.items(items);const req=randomUUID();const a=await(await f.batch([items[0]],{request_id:req})).json();const b=await(await f.batch([items[0]],{request_id:req})).json();assert.deepEqual(a.ids,b.ids);assert.equal((await f.job()).command.selected,1);assert.equal((await f.batch([items[1]],{request_id:req})).status,409);});
test('interrupted batch transaction leaves no lease, lost item or consumed count',async()=>{const f=await fixture(),item=entry();await f.items([item]);f.storage.fail='org4-batch:';assert.equal((await f.batch([item])).status,500);assert.equal((await f.storage.list({prefix:'org4-lock:'})).size,0);assert.equal((await f.storage.get(`org4-item:${f.id}:${item.id}`)).batch_id,null);assert.equal((await f.job()).command.selected,0);assert.equal((await f.batch([item])).status,201);});
test('interrupted command does not create an acknowledged command without its job revision',async()=>{const f=await fixture(),revision=(await f.job()).revision,request_id=randomUUID();f.storage.fail='org4-job:';assert.equal((await f.command(0,'pause',{request_id,revision})).status,500);assert.equal(await f.storage.get(`org4-command:${f.id}:${request_id}`),undefined);assert.equal((await f.job()).revision,revision);});
test('metadata does not count as upload; actual full bytes bind the original version',async()=>{const f=await fixture(),[item]=await selected(f);assert.equal((await f.receipt(item,'uploaded')).status,409);const {response,id}=await f.file(item);assert.equal(response.status,201);const row=(await(await f.call(f.path+'/items')).json()).items[0];assert.equal(row.received,true);assert.equal(row.file.id,id);assert.equal(row.file.bytes,item.bytes);assert.deepEqual(new Uint8Array(await(await f.call('/v2/files/'+id)).arrayBuffer()),new TextEncoder().encode('Exerciții de matematică pentru școală.'));assert.equal((await f.job()).counters.uploaded,1);});
test('upload rejects mismatched original identity even when byte hash is identical',async()=>{const f=await fixture(),[item]=await selected(f);assert.equal((await f.file(item,{headers:{'x-original-id':randomUUID()}})).response.status,409);assert.equal((await f.storage.list({prefix:'cloud-file:'})).size,0);});
test('moves require ready plus acknowledged intent plus verified target hash',async()=>{const f=await fixture(),[item]=await selected(f);assert.equal((await f.receipt(item,'applying')).status,409);assert.equal((await f.receipt(item,'moved',{target_sha256:item.sha256})).status,409);await ready(f,item);assert.equal((await f.receipt(item,'applying')).status,200);assert.equal((await f.receipt(item,'moved',{target_sha256:'a'.repeat(64)})).status,409);assert.equal((await f.receipt(item,'moved',{target_sha256:item.sha256})).status,200);assert.equal((await f.job()).counters.moved,1);assert.equal((await f.receipt(item,'moved',{target_sha256:item.sha256})).status,200);assert.equal((await f.job()).counters.moved,1);});
test('cancel or grant revocation blocks new actions but accepts already begun move facts',async()=>{const f=await fixture(),items=await selected(f,[entry(),entry()]);await ready(f,items[0]);await f.receipt(items[0],'applying');const d=await f.storage.get('cleanup-device:'+f.device);d.grant.enabled=false;await f.storage.put('cleanup-device:'+f.device,d);assert.equal((await f.receipt(items[1],'analyzed')).status,423);assert.equal((await f.receipt(items[0],'moved',{target_sha256:items[0].sha256})).status,200);assert.equal((await f.job()).state,'access_needed');});
test('copied but not removed is distinct and the next receipt reconciles the same operation',async()=>{const f=await fixture(),[item]=await selected(f);await ready(f,item);await f.receipt(item,'applying');assert.equal((await f.receipt(item,'copied_pending_removal',{target_sha256:item.sha256})).status,200);assert.equal((await f.job()).counters.moved,0);assert.equal((await f.job()).counters.copied_pending_removal,1);assert.equal((await f.receipt({...item,operation_id:randomUUID()},'moved',{target_sha256:item.sha256})).status,409);await f.receipt(item,'moved',{target_sha256:item.sha256});assert.equal((await f.job()).counters.copied_pending_removal,0);});
test('receipt pages are atomic and cannot partially move before a bad receipt',async()=>{const f=await fixture(),[item]=await selected(f);await ready(f,item);await f.receipt(item,'applying');const r=await f.call(f.path+'/receipts','POST',{grant_id:f.grant,receipts:[{id:item.id,operation_id:item.operation_id,state:'moved',source_sha256:item.sha256,target_sha256:item.sha256},{id:randomUUID(),operation_id:randomUUID(),state:'moved',source_sha256:item.sha256,target_sha256:item.sha256}]});assert.equal(r.status,409);assert.equal((await f.job()).counters.applying,1);assert.equal((await f.job()).counters.moved,0);});
test('progress survives copy and extracted content expiry without renewing move approval',async t=>{const f=await fixture(),i=entry();i.extraction={source_sha256:i.sha256,method:'utf8',text:'Text',partial:false};const [item]=await selected(f,[i]);await moved(f,item);const now=Date.now();t.mock.method(Date,'now',()=>now+TTL+1);await f.account.alarm();assert.equal((await f.job()).counters.moved,1);const row=(await(await f.call(f.path+'/items')).json()).items[0];assert.equal(row.received,false);assert.equal(row.file,null);assert.equal((await f.storage.list({prefix:'org4-content:'})).size,0);});
test('two successive next-N commands continue without selecting moved originals again',async()=>{const f=await fixture({count:1}),items=[entry(),entry()];await f.items(items,{inventory_complete:true});await f.batch([items[0]]);items[0].operation_id=randomUUID();await moved(f,items[0]);assert.equal((await f.job()).command.status,'complete');assert.equal((await f.command(1)).status,200);const second=await(await f.batch([items[1]])).json();assert.deepEqual(second.ids,[items[1].id]);await f.items([{...entry(),original_id:items[0].original_id,sha256:items[0].sha256,version:items[0].version,modified_at:Date.now()+10000}]);assert.equal((await f.job()).counters.total,2);});
test('new content hash of the same original is a distinct eligible version',async()=>{const f=await fixture(),[item]=await selected(f);await moved(f,item);const bytes=new TextEncoder().encode('Conținut schimbat');const fresh=entry({original_id:item.original_id,sha256:hash(bytes),version:hash(bytes),bytes:bytes.length});assert.equal((await f.items([fresh])).status,200);assert.equal((await f.job()).counters.total,2);});
test('cross-job original leases prevent two simultaneous mutations',async()=>{const f=await fixture(),[item]=await selected(f);const spec={...f.spec,id:randomUUID()};const j=await(await f.call(f.root,'POST',spec)).json();const base=f.root+'/'+j.id;await f.call(base+'/command','POST',{request_id:randomUUID(),revision:j.revision,action:'continue',count:1});const copy={...entry(),original_id:item.original_id};await f.call(base+'/items','POST',{grant_id:f.grant,items:[copy]});const b=await(await f.call(base+'/batch','POST',{request_id:randomUUID(),grant_id:f.grant,limit:1,ids:[copy.id]})).json();assert.equal(b.ids.length,0);});
test('manual approval is explicit, scoped and atomic',async()=>{const f=await fixture({spec:{auto_apply:false}}),[item]=await selected(f);await f.file(item);assert.equal((await f.receipt(item,'ready',{destination:'FORJA/Școală'})).status,403);const request={request_id:randomUUID(),revision:(await f.job()).revision,confirm:true,items:[{id:item.id,destination:'FORJA/Școală'}]};f.storage.fail='org4-approval:';assert.equal((await f.call(f.path+'/approve','POST',request)).status,500);assert.equal((await f.job()).counters.ready,0);assert.equal((await f.call(f.path+'/approve','POST',request)).status,200);assert.equal((await f.receipt(item,'applying')).status,200);});
test('local analysis can move originals without inventing a cloud upload',async()=>{const f=await fixture({spec:{mode:'local',ai_consent:false}}),[item]=await selected(f);assert.equal((await f.receipt(item,'ready',{destination:'FORJA/Școală'})).status,409);await f.receipt(item,'analyzed',{destination:'FORJA/Școală',reason:'Text educațional citit pe telefon'});assert.equal((await f.receipt(item,'ready',{destination:'FORJA/Școală'})).status,200);await f.receipt(item,'applying');await f.receipt(item,'moved',{target_sha256:item.sha256});const row=(await(await f.call(f.path+'/items')).json()).items[0];assert.equal(row.received,false);assert.equal(row.state,'moved');assert.equal((await f.job()).counters.uploaded,0);});
test('website folder change queues a phone move and never reports a virtual rename as applied',async()=>{const f=await fixture({spec:{auto_apply:false}}),[item]=await selected(f),copy=await f.file(item);assert.equal((await f.call('/v2/files/'+copy.id,'PATCH',{folder:'FORJA/Acte'})).status,400);const v={folder:'FORJA/Acte',request_id:randomUUID(),revision:(await f.job()).revision};const response=await f.call('/v2/files/'+copy.id,'PATCH',v);assert.equal(response.status,200);const result=await response.json();assert.equal(result.folder,'Documente');assert.equal(result.pending_folder,'FORJA/Acte');assert.equal(result.sync_state,'awaiting_phone');assert.equal((await f.call('/v2/files/'+copy.id,'PATCH',v)).status,200);assert.equal((await f.job()).counters.ready,1);});
test('v4 metadata is paginated and does not inherit the legacy 15,000 limit',async()=>{const f=await fixture();const j=await f.storage.get('org4-job:'+f.id);j.counters.total=15000;j.counters.pending=15000;await f.storage.put('org4-job:'+f.id,j);const items=Array.from({length:60},()=>entry());assert.equal((await f.items(items)).status,200);const page=await(await f.call(f.path+'/items')).json();assert.equal(page.total,15060);assert.equal(page.items.length,50);const next=await(await f.call(f.path+'/items?after='+page.next_cursor)).json();assert.equal(next.items.length,10);assert.equal(next.next_cursor,null);});

const aiRequest=(f,item)=>new Request('https://fixture/insights/api/organizer-analysis',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({device:f.device,job:f.id,ids:[item.id],consent:true})});
const aiProposal=()=>({response:{destination:'Școală/Matematică',reason:'Exerciții de matematică.',confidence:'high',evidence:[{source_id:'text',quote:'Exerciții de matematică',observation:''}]}});
test('content AI orchestration reads real owned bytes, saves attributed evidence and reuses the cached result',async()=>{const f=await fixture(),[item]=await selected(f);await f.file(item);let calls=0;const env={AI:{run:async(model,input)=>{calls++;assert.match(input.messages[1].content,/matematică/);return aiProposal();}}};const r=await organizeJobAI(aiRequest(f,item),env,'alice',f.account);assert.equal(r.status,200);const row=(await(await f.call(f.path+'/items')).json()).items[0];assert.equal(row.destination,'FORJA/Școală/Matematică');assert.equal(row.analysis.source_sha256,item.sha256);assert.equal(row.analysis.evidence[0].quote,'Exerciții de matematică');assert.equal(row.coverage.status,'complete');assert.equal(row.state,'uploaded');await organizeJobAI(aiRequest(f,item),env,'alice',f.account);assert.equal(calls,1);assert.equal((await f.storage.get('organizer-ai-budget')).used,1);});
test('revocation during real content inference discards the result',async()=>{const f=await fixture(),[item]=await selected(f);await f.file(item);const env={AI:{run:async()=>{const d=await f.storage.get('cleanup-device:'+f.device);d.grant.id=randomUUID();await f.storage.put('cleanup-device:'+f.device,d);return aiProposal();}}};await assert.rejects(()=>organizeJobAI(aiRequest(f,item),env,'alice',f.account));assert.equal((await f.storage.list({prefix:'org4-content:'})).size,0);});
test('deleting the source copy during inference prevents late derived content from being saved',async()=>{const f=await fixture(),[item]=await selected(f),file=await f.file(item);const env={AI:{run:async()=>{await f.call('/v2/files/'+file.id,'DELETE');return aiProposal();}}};await assert.rejects(()=>organizeJobAI(aiRequest(f,item),env,'alice',f.account));assert.equal((await f.storage.list({prefix:'org4-content:'})).size,0);});
test('an AI response cannot replace a destination already explicitly approved during inference',async()=>{const f=await fixture({spec:{auto_apply:false}}),[item]=await selected(f);await f.file(item);const env={AI:{run:async()=>{const r=await f.call(f.path+'/approve','POST',{request_id:randomUUID(),revision:(await f.job()).revision,confirm:true,items:[{id:item.id,destination:'FORJA/Ales de mine'}]});assert.equal(r.status,200);return aiProposal();}}};await organizeJobAI(aiRequest(f,item),env,'alice',f.account);const row=(await(await f.call(f.path+'/items')).json()).items[0];assert.equal(row.destination,'FORJA/Ales de mine');assert.equal(row.state,'ready');});
test('forgetting a job never deletes a phone original or allows delayed recreation',async()=>{const f=await fixture(),[item]=await selected(f);const file=await f.file(item);assert.equal((await f.call(f.path,'DELETE')).status,202);assert.equal((await f.call(f.root,'POST',f.spec)).status,410);assert.equal((await f.receipt(item,'analyzed')).status,410);await f.account.alarm();await f.account.alarm();assert.equal((await f.storage.list({prefix:`org4-item:${f.id}:`})).size,0);assert.equal((await f.call('/v2/files/'+file.id)).status,200);});
test('forgetting progress is blocked while a move needs reconciliation',async()=>{const f=await fixture(),[item]=await selected(f);await ready(f,item);await f.receipt(item,'applying');assert.equal((await f.call(f.path,'DELETE')).status,409);assert.equal((await f.job()).counters.applying,1);});
test('ambiguous provider outcomes keep the original locked until the same intent is reconciled',async()=>{const f=await fixture(),[item]=await selected(f);await ready(f,item);await f.receipt(item,'applying');assert.equal((await f.receipt(item,'failed_retryable')).status,409);assert.equal((await f.receipt(item,'needs_review',{message:'Răspuns pierdut după scriere.'})).status,200);assert.equal((await f.job()).unresolved,1);await f.command(0,'cancel');assert.equal((await f.call(f.path,'DELETE')).status,409);assert.equal((await f.storage.list({prefix:'org4-lock:'})).size,1);assert.equal((await f.receipt(item,'moved',{target_sha256:item.sha256})).status,200);assert.equal((await f.job()).unresolved,0);assert.equal((await f.storage.list({prefix:'org4-lock:'})).size,0);});
test('lost upload binding writes retry without losing uploaded counters',async()=>{const f=await fixture(),[item]=await selected(f);const id=randomUUID();f.storage.fail='org4-job:';assert.equal((await f.file(item,{id})).response.status,500);assert.equal((await f.job()).counters.uploaded,0);assert.equal((await f.file(item,{id})).response.status,200);assert.equal((await f.job()).counters.uploaded,1);});
