import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID,randomBytes} from 'node:crypto';import {InsightsAccount} from './insights-store.mjs';
class Storage{m=new Map();async get(k){return structuredClone(this.m.get(k));}async put(k,v){this.m.set(k,structuredClone(v));}async delete(keys){for(const k of Array.isArray(keys)?keys:[keys])this.m.delete(k);}async list({prefix}){return new Map([...this.m].filter(([k])=>k.startsWith(prefix)).map(([k,v])=>[k,structuredClone(v)]));}async getAlarm(){return this.alarm;}async setAlarm(n){this.alarm=n;}async deleteAlarm(){this.alarm=null;}}
function fixture(){const storage=new Storage();let queue=Promise.resolve();const account=new InsightsAccount({storage,blockConcurrencyWhile(fn){const job=queue.then(fn);queue=job.catch(()=>{});return job;}},{RECORDS:{}});const call=async(path,method='GET',body,uid='alice')=>{const r=await account.fetch(new Request('https://forja.test/v2/recovery/'+path,{method,headers:{'content-type':'application/json','x-forja-owner':uid},...(body?{body:JSON.stringify(body)}:{})}));return {status:r.status,...await r.json()};};return {account,storage,call};}
async function enroll(f){const id=randomUUID(),secret=randomBytes(32).toString('hex');assert.equal((await f.call(`devices/${id}/grant`,'POST',{name:'Telefon Alice',secret,consent:true})).status,200);return {id,secret};}
/** A 4.4 phone: enrolled by the signed contract v3, already beating (protocol 2). */
async function enrollV2(f){const id=randomUUID(),secret=randomBytes(32).toString('hex');assert.equal((await f.call(`devices/${id}/grant`,'POST',{name:'Galaxy S23',secret,basis:'contract',contract_version:3})).status,200);const d={id,secret};assert.equal((await beat(f,d)).status,200);return d;}
const route=(d,action)=>`devices/${d.id}/${action}`;
const beat=(f,d,extra={})=>f.call(route(d,'beat'),'POST',{secret:d.secret,status:'ready',...extra});
async function start(f,d){const id=randomUUID();const r=await f.call(route(d,'command'),'POST',{id,minutes:15});assert.equal(r.status,202);return r.command;}
async function ring(f,d,seconds=60){const r=await f.call(route(d,'command'),'POST',{id:randomUUID(),kind:'ring',seconds});assert.equal(r.status,202);return r.command;}
const ack=(f,d,c,status='locating')=>f.call(route(d,'status'),'POST',{secret:d.secret,command:c.id,status});
const fix=(d,c,extra={})=>({secret:d.secret,command:c.id,lat:45.1,lon:24.3,accuracy:8,at:Date.now(),battery:70,...extra});
const row=async f=>(await f.call('devices')).devices[0];
test('web cannot start recovery without phone enrollment; enrollment does not start GPS',async()=>{const f=fixture(),id=randomUUID();assert.equal((await f.call(`devices/${id}/command`,'POST',{id:randomUUID(),minutes:15})).status,404);assert.equal((await f.call(`devices/${id}/grant`,'POST',{name:'Telefon',secret:randomBytes(32).toString('hex'),consent:false})).status,403);const d=await enroll(f);const list=await f.call('devices');assert.equal(list.devices[0].command,null);assert.equal(list.devices[0].position,null);assert.equal(list.devices[0].last,null);assert.equal(list.devices[0].online,false);assert.equal(list.devices[0].basis,'consent');assert.equal(list.retention_hours,24);assert.equal(list.last_retention_days,7);assert(!JSON.stringify(list).includes(d.secret));assert(!JSON.stringify(list).includes('secret_hash'));});
test('another account cannot list, start or read the enrolled phone',async()=>{const f=fixture(),d=await enroll(f);for(const [path,method,body]of [['devices','GET'],[route(d,'command'),'POST',{id:randomUUID(),minutes:15}],[route(d,'poll'),'POST',{secret:d.secret,status:'ready'}],[route(d,'beat'),'POST',{secret:d.secret,status:'ready'}],[`devices/${d.id}`,'PATCH',{name:'Al meu'}]])assert.equal((await f.call(path,method,body,'bob')).status,403);const other=fixture();assert.equal((await other.call(route(d,'command'),'POST',{id:randomUUID(),minutes:15},'bob')).status,404);});
test('device secret is required for polling, beats, acknowledgments and positions',async()=>{const f=fixture(),d=await enroll(f),c=await start(f,d),bad='0'.repeat(64);assert.equal((await f.call(route(d,'poll'),'POST',{secret:bad,status:'ready'})).status,403);assert.equal((await f.call(route(d,'beat'),'POST',{secret:bad,status:'ready'})).status,403);assert.equal((await f.call(route(d,'status'),'POST',{secret:bad,command:c.id,status:'locating'})).status,403);assert.equal((await f.call(route(d,'position'),'POST',fix(d,c,{secret:bad}))).status,403);assert.equal((await f.call(route(d,'position'),'POST',fix(d,c))).status,409);});
test('queued request, phone confirmation and fresh measured coordinates have distinct states',async()=>{const f=fixture(),d=await enroll(f),c=await start(f,d);assert.equal(c.phase,'queued');assert.equal(c.kind,'locate');assert.equal(c.minutes,15);assert.equal(c.seconds,null);assert.equal((await f.call(route(d,'poll'),'POST',{secret:d.secret,status:'ready'})).command.id,c.id);const a=await ack(f,d,c);assert.equal(a.status,200);assert.equal(a.command.phase,'active');assert.equal((await f.call(route(d,'position'),'POST',fix(d,c))).status,200);const r=await row(f);assert.equal(r.command.phase,'active');assert.equal(r.position.accuracy,8);assert.equal(r.position.fresh,true);assert.equal(r.online,true);assert.equal(r.battery,70);assert.equal(r.last.accuracy,8,'a search position is also the last known point');});
test('the minutes of a search start when the phone confirms, not when the site asks',async t=>{const f=fixture(),d=await enroll(f),c=await start(f,d);const later=c.created_at+20*60000;t.mock.method(Date,'now',()=>later);const a=await ack(f,d,c);assert.equal(a.command.until,later+15*60000);});
test('web stop closes the request, rejects later phone writes and KEEPS the last position',async()=>{const f=fixture(),d=await enroll(f),c=await start(f,d);await ack(f,d,c);await f.call(route(d,'position'),'POST',fix(d,c));assert.equal((await f.call(route(d,'command?id='+c.id),'DELETE')).status,200);assert.equal((await f.call(route(d,'position'),'POST',fix(d,c,{at:Date.now()+1}))).status,409);const r=await row(f);assert.equal(r.command,null);assert.equal(r.status,'stopped');assert.equal(r.position.lat,45.1,'the search position stays for 24 h');assert.equal(r.last.lat,45.1);assert.equal((await f.call(route(d,'command'),'POST',{id:c.id,minutes:15})).status,409);});
test('phone stop ("Am găsit telefonul") keeps last and position',async()=>{const f=fixture(),d=await enroll(f),c=await start(f,d);await ack(f,d,c);await f.call(route(d,'position'),'POST',fix(d,c));assert.equal((await f.call(route(d,'stop'),'POST',{secret:d.secret,command:c.id})).status,200);const r=await row(f);assert.equal(r.command,null);assert.equal(r.status,'stopped');assert.notEqual(r.position,null);assert.notEqual(r.last,null);});
test('pending requests wait 30 minutes for a sleeping phone and cannot start later',async t=>{const f=fixture(),d=await enrollV2(f),c=await start(f,d);assert.equal(c.start_before-c.created_at,30*60000);t.mock.method(Date,'now',()=>c.created_at+29*60000);assert.equal((await beat(f,d)).command.id,c.id,'a phone in Doze that wakes after 29 min still gets it');t.mock.method(Date,'now',()=>c.start_before+1);const b=await beat(f,d);assert.equal(b.command,null);assert.equal((await ack(f,d,c)).status,409);assert.equal((await row(f)).status,'ready');});
test('active deadline rejects later updates while last known position is visibly stale',async t=>{const f=fixture(),d=await enroll(f),c=await start(f,d);await ack(f,d,c);await f.call(route(d,'position'),'POST',fix(d,c));const now=Date.now();t.mock.method(Date,'now',()=>now+120001);assert.equal((await row(f)).position.fresh,false);t.mock.method(Date,'now',()=>c.until+1);assert.equal((await f.call(route(d,'position'),'POST',fix(d,c))).status,409);assert.equal((await row(f)).command,null);});
test('search position is erased after 24 hours, the last known point after 7 days',async t=>{const f=fixture(),d=await enroll(f),c=await start(f,d);await ack(f,d,c);const at=Date.now();await f.call(route(d,'position'),'POST',fix(d,c,{at}));t.mock.method(Date,'now',()=>at+86400001);await f.account.alarm();let saved=await f.storage.get('recovery:device:'+d.id);assert.equal(saved.position,null);assert.equal(saved.last.at,at);t.mock.method(Date,'now',()=>at+7*86400000+1);await f.account.alarm();saved=await f.storage.get('recovery:device:'+d.id);assert.equal(saved.last,null);});
test('revoke removes the enrollment and defeats old command polling',async()=>{const f=fixture(),d=await enroll(f),c=await start(f,d);await f.call(route(d,'grant'),'DELETE');assert.equal((await f.call(route(d,'poll'),'POST',{secret:d.secret,status:'ready'})).status,404);assert.equal((await f.call('devices')).devices.length,0);assert.equal((await ack(f,d,c)).status,404);const v=await enrollV2(f);assert.equal((await f.call(route(v,'revoke'),'POST',{secret:v.secret})).status,200);assert.equal((await beat(f,v)).status,404);});
test('old stop retry cannot cancel a newer request',async t=>{const f=fixture(),d=await enroll(f),a=await start(f,d);await f.call(route(d,'command?id='+a.id),'DELETE');t.mock.method(Date,'now',()=>a.created_at+30001);const b=await start(f,d);assert.equal((await f.call(route(d,'stop'),'POST',{secret:d.secret,command:a.id})).status,409);assert.equal((await row(f)).command.id,b.id);});
test('command idempotency, allowed duration and enrollment bounds',async()=>{const f=fixture(),d=await enroll(f),c=await start(f,d);assert.equal((await f.call(route(d,'command'),'POST',{id:c.id,minutes:15})).status,200);assert.equal((await f.call(route(d,'command'),'POST',{id:randomUUID(),minutes:1440})).status,400);assert.equal((await f.call(route(d,'command'),'POST',{id:randomUUID(),kind:'locate',minutes:10,seconds:60})).status,400);assert.equal((await f.call(route(d,'command'),'POST',{id:randomUUID(),kind:'dance'})).status,400);for(let i=0;i<4;i++)await enroll(f);assert.equal((await f.call(`devices/${randomUUID()}/grant`,'POST',{name:'Extra',secret:randomBytes(32).toString('hex'),consent:true})).status,409);});
test('reject fabricated accuracy, old fixes, future fixes and unrelated command ids',async()=>{const f=fixture(),d=await enroll(f),c=await start(f,d);await ack(f,d,c);for(const extra of [{accuracy:-1},{lat:91},{at:Date.now()-100000},{at:Date.now()+60000},{charging:'da'}])assert.equal((await f.call(route(d,'position'),'POST',fix(d,c,extra))).status,400);assert.equal((await f.call(route(d,'position'),'POST',fix(d,c,{command:randomUUID()}))).status,409);});
test('GPS-off phone reports the real blocking state without invented position',async()=>{const f=fixture(),d=await enroll(f);await start(f,d);await f.call(route(d,'poll'),'POST',{secret:d.secret,status:'location_off'});const r=await row(f);assert.equal(r.online,true);assert.equal(r.status,'location_off');assert.equal(r.position,null);assert.equal(r.last,null);});
test('inactive enrollment expires after 30 days',async t=>{const f=fixture(),d=await enroll(f);const at=(await f.storage.get('recovery:device:'+d.id)).expires_at;t.mock.method(Date,'now',()=>at+1);assert.equal((await f.call('devices')).devices.length,0);await f.account.alarm();assert.equal(await f.storage.get('recovery:device:'+d.id),undefined);assert.equal((await f.call(route(d,'poll'),'POST',{secret:d.secret,status:'ready'})).status,404);});

// ── Protocol 2 (4.4): contract-basis enrollment, beat, ring, extend, rename ──
test('contract-basis grant needs contract v3; the legacy consent grant still works',async()=>{const f=fixture(),secret=()=>randomBytes(32).toString('hex');
 assert.equal((await f.call(`devices/${randomUUID()}/grant`,'POST',{name:'Galaxy S23',secret:secret(),basis:'contract',contract_version:2})).status,403);
 assert.equal((await f.call(`devices/${randomUUID()}/grant`,'POST',{name:'Galaxy S23',secret:secret(),basis:'contract'})).status,403);
 assert.equal((await f.call(`devices/${randomUUID()}/grant`,'POST',{name:'Galaxy S23',secret:secret(),basis:'manual',contract_version:3})).status,400);
 assert.equal((await f.call(`devices/${randomUUID()}/grant`,'POST',{name:'Galaxy S23',secret:secret(),consent:true,contract_version:3})).status,403);
 const d=await enrollV2(f);const r=await row(f);assert.equal(r.basis,'contract');assert.equal(r.name,'Galaxy S23');assert.equal((await f.storage.get('recovery:device:'+d.id)).contract_version,3);
 assert.equal((await f.call(`devices/${d.id}/grant`,'POST',{name:'Galaxy S23',secret:d.secret,basis:'contract',contract_version:3})).status,200,'re-grant with the same secret is idempotent');
 assert.equal((await f.call(`devices/${d.id}/grant`,'POST',{name:'Galaxy S23',secret:secret(),basis:'contract',contract_version:3})).status,409,'another secret cannot take the id');
 const old=await enroll(f);assert.equal((await f.call('devices')).devices.find(x=>x.id===old.id).basis,'consent');});
test('a beat without a fix marks the phone alive and changes nothing else',async()=>{const f=fixture(),d=await enrollV2(f);const b=await beat(f,d,{status:'notification_missing'});assert.equal(b.status,200);assert.equal(b.command,null);assert.equal(b.next_s,60);const r=await row(f);assert.equal(r.online,true);assert.equal(r.status,'notification_missing');assert.equal(r.last,null);assert.equal(r.position,null);assert.equal(r.battery,null);assert.equal(r.charging,null);
 assert.equal((await beat(f,d,{battery:64,charging:true,fix:null})).status,200);const s=await row(f);assert.equal(s.battery,64);assert.equal(s.charging,true);
 for(const extra of [{battery:101},{charging:'da'},{status:'dancing'},{fix:{lat:45,lon:24,accuracy:5}},{fix:{lat:95,lon:24,accuracy:5,at:Date.now()}},{extra:1}])assert.equal((await beat(f,d,extra)).status,400);});
test('the last known point only moves forward in time',async()=>{const f=fixture(),d=await enrollV2(f),now=Date.now();
 await beat(f,d,{fix:{lat:44.4,lon:26.1,accuracy:12,at:now-60000}});assert.deepEqual((await row(f)).last,{lat:44.4,lon:26.1,accuracy:12,at:now-60000});
 await beat(f,d,{fix:{lat:10,lon:10,accuracy:5,at:now-120000}});assert.equal((await row(f)).last.lat,44.4,'an older fix sent late is ignored, not an error');
 await beat(f,d,{fix:{lat:44.5,lon:26.2,accuracy:9,at:now-1000}});assert.equal((await row(f)).last.lat,44.5);
 assert.equal((await beat(f,d,{fix:{lat:1,lon:1,accuracy:5,at:now-8*86400000}})).status,400,'older than the 7-day retention');
 const c=await start(f,d);await ack(f,d,c);await f.call(route(d,'position'),'POST',fix(d,c,{lat:44.6,at:now}));assert.equal((await row(f)).last.lat,44.6);
 await beat(f,d,{fix:{lat:3,lon:3,accuracy:5,at:now-500}});assert.equal((await row(f)).last.lat,44.6);});
test('ring lifecycle: queued, ringing, one position, found — the phone keeps its last point',async()=>{const f=fixture(),d=await enrollV2(f);await beat(f,d,{fix:{lat:44.4,lon:26.1,accuracy:20,at:Date.now()-5000}});
 const c=await ring(f,d);assert.equal(c.kind,'ring');assert.equal(c.seconds,60);assert.equal(c.minutes,null);assert.equal(c.phase,'queued');
 const b=await beat(f,d);assert.equal(b.command.id,c.id);assert.equal(b.command.kind,'ring');assert.equal(b.next_s,15);
 const a=await ack(f,d,c,'ringing');assert.equal(a.command.phase,'active');assert(a.command.until-Date.now()<=60000&&a.command.until-Date.now()>55000);
 assert.equal((await row(f)).status,'ringing');
 assert.equal((await f.call(route(d,'position'),'POST',fix(d,c,{lat:44.41}))).status,200);assert.equal((await row(f)).status,'ringing','a ring position does not turn the state into locating');
 assert.equal((await f.call(route(d,'status'),'POST',{secret:d.secret,command:c.id,status:'found'})).status,200);
 const r=await row(f);assert.equal(r.command,null);assert.equal(r.status,'found');assert.equal(r.last.lat,44.41);assert.equal(r.position.lat,44.41);});
test('ring needs a protocol-2 phone, valid seconds, and replaces an active locate',async t=>{const f=fixture(),old=await enroll(f);assert.equal((await f.call(route(old,'command'),'POST',{id:randomUUID(),kind:'ring',seconds:60})).status,409);
 const d=await enrollV2(f);assert.equal((await f.call(route(d,'command'),'POST',{id:randomUUID(),kind:'ring',seconds:45})).status,400);assert.equal((await f.call(route(d,'command'),'POST',{id:randomUUID(),kind:'ring',minutes:10})).status,400);
 const c=(await f.call(route(d,'command'),'POST',{id:randomUUID(),kind:'locate',minutes:10})).command;assert.equal(c.minutes,10);
 const r=await ring(f,d,30);assert.equal((await f.call('devices')).devices.find(x=>x.id===d.id).command.id,r.id,'Sună while tracking takes over at once');
 assert.equal((await f.call(route(d,'command'),'POST',{id:randomUUID(),kind:'locate',minutes:10})).status,409,'a locate never interrupts a ring');
 assert.equal((await f.call(route(d,'command'),'POST',{id:randomUUID(),kind:'ring'})).status,409);
 const defaulted=fixture(),e=await enrollV2(defaulted);assert.equal((await defaulted.call(route(e,'command'),'POST',{id:randomUUID(),kind:'ring'})).command.seconds,60);});
test('extend adds minutes to a locate, capped at 60 minutes in total',async()=>{const f=fixture(),d=await enrollV2(f);const c=(await f.call(route(d,'command'),'POST',{id:randomUUID(),kind:'locate',minutes:10})).command;const a=await ack(f,d,c);
 const e=await f.call(route(d,'extend'),'POST',{command:c.id,minutes:10});assert.equal(e.status,200);assert.equal(e.command.minutes,20);assert.equal(e.command.until,a.command.until+10*60000);
 for(let i=0;i<4;i++)assert.equal((await f.call(route(d,'extend'),'POST',{command:c.id,minutes:10})).status,200);
 assert.equal((await row(f)).command.minutes,60);assert.equal((await f.call(route(d,'extend'),'POST',{command:c.id,minutes:10})).status,409);
 assert.equal((await f.call(route(d,'extend'),'POST',{command:randomUUID(),minutes:10})).status,409);assert.equal((await f.call(route(d,'extend'),'POST',{command:c.id,minutes:0})).status,400);
 const g=fixture(),p=await enrollV2(g),r=await ring(g,p);assert.equal((await g.call(route(p,'extend'),'POST',{command:r.id,minutes:10})).status,409,'a ring is not extended');});
test('rename from the site: at most 40 characters and it survives a phone re-grant',async()=>{const f=fixture(),d=await enrollV2(f);const r=await f.call(`devices/${d.id}`,'PATCH',{name:'  Telefonul Lanei  '});assert.equal(r.status,200);assert.equal(r.device.name,'Telefonul Lanei');
 for(const name of ['', '   ','x'.repeat(41),'a\nb',7])assert.equal((await f.call(`devices/${d.id}`,'PATCH',{name})).status,400);
 assert.equal((await f.call(`devices/${d.id}`,'PATCH',{name:'Ok',secret:d.secret})).status,400);
 await f.call(`devices/${d.id}/grant`,'POST',{name:'Galaxy S23',secret:d.secret,basis:'contract',contract_version:3});assert.equal((await row(f)).name,'Telefonul Lanei');
 assert.equal((await f.call(`devices/${randomUUID()}`,'PATCH',{name:'Nimeni'})).status,404);assert.equal((await f.call(`devices/${d.id}`,'DELETE')).status,404);});
test('a poll-only 4.3 phone keeps working next to protocol 2 routes',async()=>{const f=fixture(),d=await enroll(f),c=await start(f,d);const p=await f.call(route(d,'poll'),'POST',{secret:d.secret,status:'ready'});assert.equal(p.command.id,c.id);assert.equal(p.next_s,undefined);await ack(f,d,c);await f.call(route(d,'position'),'POST',fix(d,c));assert.equal((await f.call(route(d,'stop'),'POST',{secret:d.secret,command:c.id})).status,200);assert.equal((await row(f)).command,null);});
