import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID,randomBytes} from 'node:crypto';import {InsightsAccount} from './insights-store.mjs';
class Storage{m=new Map();async get(k){return structuredClone(this.m.get(k));}async put(k,v){this.m.set(k,structuredClone(v));}async delete(keys){for(const k of Array.isArray(keys)?keys:[keys])this.m.delete(k);}async list({prefix}){return new Map([...this.m].filter(([k])=>k.startsWith(prefix)).map(([k,v])=>[k,structuredClone(v)]));}async getAlarm(){return this.alarm;}async setAlarm(n){this.alarm=n;}async deleteAlarm(){this.alarm=null;}}
function fixture(){const storage=new Storage();let queue=Promise.resolve();const account=new InsightsAccount({storage,blockConcurrencyWhile(fn){const job=queue.then(fn);queue=job.catch(()=>{});return job;}},{RECORDS:{}});const call=async(path,method='GET',body,uid='alice')=>{const r=await account.fetch(new Request('https://forja.test/v2/recovery/'+path,{method,headers:{'content-type':'application/json','x-forja-owner':uid},...(body?{body:JSON.stringify(body)}:{})}));return {status:r.status,...await r.json()};};return {account,storage,call};}
async function enroll(f){const id=randomUUID(),secret=randomBytes(32).toString('hex');assert.equal((await f.call(`devices/${id}/grant`,'POST',{name:'Telefon Alice',secret,consent:true})).status,200);return {id,secret};}
const route=(d,action)=>`devices/${d.id}/${action}`;
async function start(f,d){const id=randomUUID();const r=await f.call(route(d,'command'),'POST',{id,minutes:15});assert.equal(r.status,202);return r.command;}
const ack=(f,d,c)=>f.call(route(d,'status'),'POST',{secret:d.secret,command:c.id,status:'locating'});
const fix=(d,c,extra={})=>({secret:d.secret,command:c.id,lat:45.1,lon:24.3,accuracy:8,at:Date.now(),battery:70,...extra});
test('web cannot start recovery without phone enrollment; enrollment does not start GPS',async()=>{const f=fixture(),id=randomUUID();assert.equal((await f.call(`devices/${id}/command`,'POST',{id:randomUUID(),minutes:15})).status,404);assert.equal((await f.call(`devices/${id}/grant`,'POST',{name:'Telefon',secret:randomBytes(32).toString('hex'),consent:false})).status,403);const d=await enroll(f);const list=await f.call('devices');assert.equal(list.devices[0].command,null);assert.equal(list.devices[0].position,null);assert.equal(list.devices[0].online,false);assert(!JSON.stringify(list).includes(d.secret));assert(!JSON.stringify(list).includes('secret_hash'));});
test('another account cannot list, start or read the enrolled phone',async()=>{const f=fixture(),d=await enroll(f);for(const [path,method,body]of [['devices','GET'],[route(d,'command'),'POST',{id:randomUUID(),minutes:15}],[route(d,'poll'),'POST',{secret:d.secret,status:'ready'}]])assert.equal((await f.call(path,method,body,'bob')).status,403);const other=fixture();assert.equal((await other.call(route(d,'command'),'POST',{id:randomUUID(),minutes:15},'bob')).status,404);});
test('device secret is required for polling, acknowledgments and positions',async()=>{const f=fixture(),d=await enroll(f),c=await start(f,d),bad='0'.repeat(64);assert.equal((await f.call(route(d,'poll'),'POST',{secret:bad,status:'ready'})).status,403);assert.equal((await f.call(route(d,'status'),'POST',{secret:bad,command:c.id,status:'locating'})).status,403);assert.equal((await f.call(route(d,'position'),'POST',fix(d,c,{secret:bad}))).status,403);assert.equal((await f.call(route(d,'position'),'POST',fix(d,c))).status,409);});
test('queued request, phone confirmation and fresh measured coordinates have distinct states',async()=>{const f=fixture(),d=await enroll(f),c=await start(f,d);assert.equal(c.phase,'queued');assert.equal((await f.call(route(d,'poll'),'POST',{secret:d.secret,status:'ready'})).command.id,c.id);assert.equal((await ack(f,d,c)).status,200);assert.equal((await f.call(route(d,'position'),'POST',fix(d,c))).status,200);const row=(await f.call('devices')).devices[0];assert.equal(row.command.phase,'active');assert.equal(row.position.accuracy,8);assert.equal(row.position.fresh,true);assert.equal(row.online,true);});
test('web stop invalidates phone writes immediately and erases the saved position',async()=>{const f=fixture(),d=await enroll(f),c=await start(f,d);await ack(f,d,c);await f.call(route(d,'position'),'POST',fix(d,c));assert.equal((await f.call(route(d,'command?id='+c.id),'DELETE')).status,200);assert.equal((await f.call(route(d,'position'),'POST',fix(d,c))).status,409);const row=(await f.call('devices')).devices[0];assert.equal(row.command,null);assert.equal(row.position,null);assert.equal((await f.call(route(d,'command'),'POST',{id:c.id,minutes:15})).status,409);});
test('pending requests expire after five minutes and cannot start later',async t=>{const f=fixture(),d=await enroll(f),c=await start(f,d);t.mock.method(Date,'now',()=>c.start_before+1);assert.equal((await f.call(route(d,'poll'),'POST',{secret:d.secret,status:'ready'})).command,null);assert.equal((await ack(f,d,c)).status,409);});
test('active deadline rejects later updates while last known position is visibly stale',async t=>{const f=fixture(),d=await enroll(f),c=await start(f,d);await ack(f,d,c);await f.call(route(d,'position'),'POST',fix(d,c));const now=Date.now();t.mock.method(Date,'now',()=>now+120001);assert.equal((await f.call('devices')).devices[0].position.fresh,false);t.mock.method(Date,'now',()=>c.until+1);assert.equal((await f.call(route(d,'position'),'POST',fix(d,c))).status,409);assert.equal((await f.call('devices')).devices[0].command,null);});
test('last position is physically erased after 24 hours',async t=>{const f=fixture(),d=await enroll(f),c=await start(f,d);await ack(f,d,c);const at=Date.now();await f.call(route(d,'position'),'POST',fix(d,c,{at}));t.mock.method(Date,'now',()=>at+86400001);await f.account.alarm();assert.equal((await f.storage.get('recovery:device:'+d.id)).position,null);});
test('revoke removes the enrollment and defeats old command polling',async()=>{const f=fixture(),d=await enroll(f),c=await start(f,d);await f.call(route(d,'grant'),'DELETE');assert.equal((await f.call(route(d,'poll'),'POST',{secret:d.secret,status:'ready'})).status,404);assert.equal((await f.call('devices')).devices.length,0);assert.equal((await ack(f,d,c)).status,404);});
test('old stop retry cannot cancel a newer request',async t=>{const f=fixture(),d=await enroll(f),a=await start(f,d);await f.call(route(d,'command?id='+a.id),'DELETE');t.mock.method(Date,'now',()=>a.created_at+30001);const b=await start(f,d);assert.equal((await f.call(route(d,'stop'),'POST',{secret:d.secret,command:a.id})).status,409);assert.equal((await f.call('devices')).devices[0].command.id,b.id);});
test('command idempotency, allowed duration and enrollment bounds',async()=>{const f=fixture(),d=await enroll(f),c=await start(f,d);assert.equal((await f.call(route(d,'command'),'POST',{id:c.id,minutes:15})).status,200);assert.equal((await f.call(route(d,'command'),'POST',{id:randomUUID(),minutes:1440})).status,400);for(let i=0;i<4;i++)await enroll(f);assert.equal((await f.call(`devices/${randomUUID()}/grant`,'POST',{name:'Extra',secret:randomBytes(32).toString('hex'),consent:true})).status,409);});
test('reject fabricated accuracy, old fixes, future fixes and unrelated command ids',async()=>{const f=fixture(),d=await enroll(f),c=await start(f,d);await ack(f,d,c);for(const extra of [{accuracy:-1},{lat:91},{at:Date.now()-100000},{at:Date.now()+60000}])assert.equal((await f.call(route(d,'position'),'POST',fix(d,c,extra))).status,400);assert.equal((await f.call(route(d,'position'),'POST',fix(d,c,{command:randomUUID()}))).status,409);});
test('GPS-off phone reports the real blocking state without invented position',async()=>{const f=fixture(),d=await enroll(f);await start(f,d);await f.call(route(d,'poll'),'POST',{secret:d.secret,status:'location_off'});const row=(await f.call('devices')).devices[0];assert.equal(row.online,true);assert.equal(row.status,'location_off');assert.equal(row.position,null);});
test('inactive enrollment expires after 30 days',async t=>{const f=fixture(),d=await enroll(f);const at=(await f.storage.get('recovery:device:'+d.id)).expires_at;t.mock.method(Date,'now',()=>at+1);assert.equal((await f.call('devices')).devices.length,0);await f.account.alarm();assert.equal(await f.storage.get('recovery:device:'+d.id),undefined);assert.equal((await f.call(route(d,'poll'),'POST',{secret:d.secret,status:'ready'})).status,404);});
