import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {SocialGraph} from './social.mjs';
class Store{m=new Map();async get(k){return structuredClone(this.m.get(k));}async put(k,v){this.m.set(k,structuredClone(v));}async delete(k){this.m.delete(k);}async list({prefix}){return new Map([...this.m].filter(([k])=>k.startsWith(prefix)));}async setAlarm(n){this.alarm=n;}async getAlarm(){return this.alarm;}async deleteAlarm(){this.alarm=null;}}
function fixture(){const storage=new Store();let queue=Promise.resolve();const graph=new SocialGraph({storage,blockConcurrencyWhile(fn){const p=queue.then(fn);queue=p.catch(()=>{});return p;}});const call=async(uid,path,method='GET',body,claims={})=>{const r=await graph.fetch(new Request('https://forja/v2/social/'+path,{method,headers:{...claims,'x-forja-owner':uid,'content-type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})}));return{status:r.status,...await r.json()};};return{storage,graph,call};}
const phones={alice:'+40721000001',bob:'+40721000002',charlie:'+40721000003',dan:'+40721000004'};
const issued=()=>({'x-forja-token-issued':String(Math.floor(Date.now()/1000))});
const verified=phone=>({'x-forja-phone':phone,...issued()});
const declared=phone=>({'x-forja-phone-declared':phone,...issued()});
const discover=(f,uid,claims=declared(phones[uid]))=>f.call(uid,'contacts/discovery','POST',{consent:true},claims);
const match=(f,uid,numbers,claims=declared(phones[uid]))=>f.call(uid,'contacts/match','POST',{numbers,consent:true},claims);
const noPhones=(f,...extra)=>{for(const value of [...f.storage.m.values(),...extra])for(const phone of Object.values(phones))assert(!JSON.stringify(value).includes(phone));};

test('a declared number registers discovery without an SMS claim and is reported as unverified',async()=>{const f=fixture();const r=await discover(f,'alice');assert.equal(r.status,200);assert.equal(r.verified,false);assert.equal((await f.call('alice','state')).me.discoverable,true);const entry=[...f.storage.m.entries()].find(([k])=>k.startsWith('phone:'))[1];assert.equal(entry.uid,'alice');assert.equal(entry.verified,false);noPhones(f,r);});
test('the gateway-set verified claim wins over a declared header that names another number',async()=>{const f=fixture();await discover(f,'alice',{...verified(phones.alice),'x-forja-phone-declared':phones.dan});await discover(f,'bob');const r=await match(f,'bob',[phones.alice,phones.dan]);assert.equal(r.matches.length,1);assert.equal(r.matches[0].index,0);assert.equal(r.matches[0].verified,true);});
test('a declared number cannot take over an active listing of another account, verified or declared',async()=>{const f=fixture();await discover(f,'alice');const dup=await discover(f,'bob',declared(phones.alice));assert.equal(dup.status,409);assert.match(dup.error,/Verifică-l prin SMS/);assert.equal((await f.call('bob','state')).me.discoverable,false);await discover(f,'charlie',verified(phones.charlie));assert.equal((await discover(f,'dan',declared(phones.charlie))).status,409);assert.equal((await discover(f,'alice')).status,200);});
test('a verified number replaces a declared listing of another account and a declared one cannot replace a verified one',async()=>{const f=fixture();await discover(f,'alice');await discover(f,'bob',verified(phones.alice));await discover(f,'charlie');const r=await match(f,'charlie',[phones.alice]);assert.equal(r.matches.length,1);assert.equal(r.matches[0].id,'bob');assert.equal(r.matches[0].verified,true);assert.equal((await match(f,'alice',[phones.bob])).status,403);assert.equal((await discover(f,'alice')).status,409);assert.equal((await discover(f,'alice',verified(phones.alice))).status,200);assert.equal((await match(f,'charlie',[phones.alice])).matches[0].id,'alice');});
test('mutual agenda entries become friends on both profiles without a request; one-sided matches stay pending-free',async()=>{const f=fixture();for(const uid of ['alice','bob','charlie'])await discover(f,uid);const first=await match(f,'alice',[phones.bob,phones.charlie]);assert.equal(first.status,200);assert.deepEqual(first.matches.map(m=>[m.id,m.friend,m.mutual]),[['bob',false,false],['charlie',false,false]]);assert.equal((await f.call('alice','state')).friends.length,0);
 const second=await match(f,'bob',[phones.alice]);assert.equal(second.matches.length,1);assert.equal(second.matches[0].mutual,true);assert.equal(second.matches[0].friend,true);assert.equal(second.matches[0].pending,false);
 assert.deepEqual((await f.call('alice','state')).friends.map(x=>x.id),['bob']);assert.deepEqual((await f.call('bob','state')).friends.map(x=>x.id),['alice']);
 const again=await match(f,'alice',[phones.bob,phones.charlie]);assert.deepEqual(again.matches.map(m=>[m.id,m.friend,m.mutual]),[['bob',true,true],['charlie',false,false]]);noPhones(f,first,second,again);});
test('mutual agenda entries never override a block and pending requests collapse into the friendship',async()=>{const f=fixture();for(const uid of ['alice','bob','charlie'])await discover(f,uid);await match(f,'charlie',[phones.alice]);await f.call('charlie','friend','POST',{id:'alice',action:'block'});assert.equal((await match(f,'alice',[phones.charlie])).matches.length,0);assert.equal((await f.call('alice','state')).friends.length,0);
 const b=await f.call('bob','state');await f.call('alice','invite','POST',{code:b.me.code});await match(f,'bob',[phones.alice]);const r=await match(f,'alice',[phones.bob]);assert.equal(r.matches[0].friend,true);const a=await f.call('alice','state');assert.equal(a.outgoing,0);assert.equal((await f.call('bob','state')).incoming.length,0);});
test('the agenda index keeps only truncated fingerprints of my numbers, capped at 5000, and expires with the listing',async t=>{const f=fixture();await discover(f,'alice');const now=Date.now();for(let page=0;page<26;page++){const numbers=Array.from({length:200},(_,i)=>'+4073'+String(page*200+i).padStart(7,'0'));assert.equal((await match(f,'alice',numbers)).status,200);}const list=await f.storage.get('contacts-of:alice');assert.equal(list.length,5000);assert(list.every(h=>/^[0-9a-f]{16}$/.test(h)));noPhones(f);
 t.mock.method(Date,'now',()=>now+31*86400000);await f.graph.alarm();assert.equal(await f.storage.get('contacts-of:alice'),undefined);assert.equal([...f.storage.m.keys()].filter(k=>k.startsWith('phone:')).length,0);});
test('opting out removes the listing and the agenda index; reciprocity then needs a fresh sync',async()=>{const f=fixture();await discover(f,'alice');await discover(f,'bob');await match(f,'alice',[phones.bob]);assert.equal((await f.call('alice','contacts/discovery','DELETE')).status,200);assert.equal(await f.storage.get('contacts-of:alice'),undefined);assert.equal([...f.storage.m.keys()].filter(k=>k.startsWith('phone:')).length,1);const r=await match(f,'bob',[phones.alice]);assert.equal(r.matches.length,0);});
test('matching without any number claim or with a malformed declared number is refused',async()=>{const f=fixture();assert.equal((await f.call('alice','contacts/discovery','POST',{consent:true},issued())).status,403);assert.equal((await f.call('alice','contacts/discovery','POST',{consent:true},declared('0721000001'))).status,403);assert.equal((await f.call('alice','contacts/discovery','POST',{consent:true},{...declared(phones.alice),'x-forja-token-issued':'1'})).status,401);});
test('the gateway forwards the declared number only under its own header and reports contacts:2 at version 17',async()=>{const src=await readFile(new URL('./insights-worker.mjs',import.meta.url),'utf8');assert.match(src,/version:17,/);assert.match(src,/contacts:2,/);assert.match(src,/headers\.set\('x-forja-phone',verifiedPhone\);headers\.set\('x-forja-phone-declared',declaredPhone\(request\)\)/);assert.match(src,/const declaredPhone = request => \{ const v = request\.headers\.get\('x-forja-phone-declared'\) \|\| ''; return \/\^\\\+\[1-9\]\[0-9\]\{7,14\}\$\/\.test\(v\) \? v : ''; \};/);
 const verify=await readFile(new URL('./verify-live.mjs',import.meta.url),'utf8');assert.match(verify,/h\.version !== 17/);assert.match(verify,/contacts: 2/);});
