import './social-contacts.test.mjs';// „Prieteni din agendă”: testele se înregistrează în același proces (node --test), fără să atingem package.json.
import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {SocialGraph,distance} from './social.mjs';
class Store{m=new Map();async get(k){return structuredClone(this.m.get(k));}async put(k,v){this.m.set(k,structuredClone(v));}async delete(k){this.m.delete(k);}async list({prefix}){return new Map([...this.m].filter(([k])=>k.startsWith(prefix)));}async setAlarm(n){this.alarm=n;}async getAlarm(){return this.alarm;}async deleteAlarm(){this.alarm=null;}}
function fixture(){const storage=new Store();let queue=Promise.resolve();const graph=new SocialGraph({storage,blockConcurrencyWhile(fn){const p=queue.then(fn);queue=p.catch(()=>{});return p;}});const call=async(uid,path,method='GET',body,claims={})=>{const r=await graph.fetch(new Request('https://forja/v2/social/'+path,{method,headers:{...claims,'x-forja-owner':uid,'content-type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})}));return{status:r.status,...await r.json()};};return{storage,graph,call};}
async function friends(f){const b=await f.call('bob','state');await f.call('alice','invite','POST',{code:b.me.code});assert.equal((await f.call('bob','friend','POST',{id:'alice',action:'accept'})).status,200);}
const start=(f,uid='alice')=>f.call(uid,'session','POST',{mode:'cycle',minutes:60,consent:true});
const fix=(id,patch={})=>({session:id,lat:45,lon:24,accuracy:5,speed:3,battery:80,at:Date.now(),...patch});
test('friend requests require explicit acceptance; no directory or unilateral location access',async()=>{const f=fixture(),a=await f.call('alice','state'),b=await f.call('bob','state');assert.equal((await f.call('alice','invite','POST',{code:b.me.code})).status,200);assert.equal((await f.call('alice','state')).friends.length,0);assert.equal((await f.call('alice','friend','POST',{id:'bob',action:'accept'})).status,409);assert.equal((await f.call('bob','friend','POST',{id:'alice',action:'accept'})).status,200);assert.equal((await f.call('bob','state')).friends[0].location,null);assert.equal((await f.call('charlie','state')).friends.length,0);assert.notEqual(a.me.code,b.me.code);});
test('session consent is required independently of friendship',async()=>{const f=fixture();await friends(f);assert.equal((await f.call('alice','session','POST',{mode:'walk',minutes:60,consent:false})).status,403);assert.equal((await f.call('alice','location','POST',fix(randomUUID()))).status,409);});
test('only accepted friends see active fresh locations; ghost invalidates old writer',async()=>{const f=fixture();await friends(f);const s=await start(f);assert.equal((await f.call('alice','location','POST',fix(s.id))).status,200);assert.equal((await f.call('bob','state')).friends[0].location.lat,45);assert.equal((await f.call('alice','session','DELETE')).status,200);assert.equal((await f.call('bob','state')).friends[0].location,null);assert.equal((await f.call('alice','location','POST',fix(s.id))).status,409);});
test('other account cannot write a session even when it knows the id',async()=>{const f=fixture();const s=await start(f);assert.equal((await f.call('bob','location','POST',fix(s.id))).status,409);});
test('position disappears after two minutes and expired sessions reject updates',async t=>{const f=fixture();await friends(f);const s=await start(f);const now=Date.now();await f.call('alice','location','POST',fix(s.id,{at:now}));t.mock.method(Date,'now',()=>now+120001);assert.equal((await f.call('bob','state')).friends[0].location,null);t.mock.method(Date,'now',()=>s.until+1);assert.equal((await f.call('alice','location','POST',fix(s.id))).status,409);await f.graph.alarm();const p=await f.storage.get('user:alice');assert.equal(p.location,null);assert.equal(p.session,null);assert.equal(p.history.length,1);});
test('block removes friendship, old messages, location and new requests',async()=>{const f=fixture();await friends(f);const s=await start(f);await f.call('alice','location','POST',fix(s.id));await f.call('alice','chat','POST',{friend:'bob',id:randomUUID(),text:'Salut'});const b=await f.call('bob','state');assert.equal((await f.call('bob','friend','POST',{id:'alice',action:'block'})).status,200);assert.equal((await f.call('bob','state')).friends.length,0);assert.equal((await f.call('alice','state')).friends.length,0);assert.equal((await f.call('alice','chat?friend=bob')).status,403);assert.equal((await f.call('alice','invite','POST',{code:b.me.code})).status,404);assert.equal(await f.storage.get('chat:alice:bob'),undefined);});
test('out of range, future and duplicate positions are rejected',async()=>{const f=fixture(),s=await start(f);assert.equal((await f.call('alice','location','POST',fix(s.id,{lat:100}))).status,400);assert.equal((await f.call('alice','location','POST',fix(s.id,{at:Date.now()+60000}))).status,400);const v=fix(s.id);assert.equal((await f.call('alice','location','POST',v)).status,200);assert.equal((await f.call('alice','location','POST',v)).status,409);});
test('saved places and exploration remain private',async()=>{const f=fixture();await friends(f);await f.call('alice','place','POST',{name:'Parc',lat:45,lon:24});const s=await start(f);await f.call('alice','location','POST',fix(s.id));const friend=(await f.call('bob','state')).friends[0];assert.equal(friend.places,undefined);assert.equal(friend.explored,undefined);assert.equal((await f.call('alice','state')).me.places.length,1);});
test('chat idempotency, maximum length and friendship enforcement',async()=>{const f=fixture();await friends(f);const m={friend:'bob',id:randomUUID(),text:'Salut 👋'};await f.call('alice','chat','POST',m);await f.call('alice','chat','POST',m);assert.equal((await f.call('bob','chat?friend=alice')).messages.length,1);assert.equal((await f.call('charlie','chat?friend=alice')).status,403);assert.equal((await f.call('alice','chat','POST',{...m,text:'x'.repeat(1001)})).status,400);});
test('group invitations require friends and do not start location sharing',async()=>{const f=fixture();await friends(f);const g={name:'Tură de seară',mode:'cycle',at:Date.now()+3600000,place:'Parc',lat:45,lon:24,friends:['bob']};const r=await f.call('alice','group','POST',g);assert.equal(r.status,200);const b=await f.call('bob','state');assert.equal(b.groups.length,1);assert.equal(b.me.session,null);assert.equal((await f.call('charlie','group-response','POST',{id:r.id,going:true})).status,403);assert.equal((await f.call('bob','group-response','POST',{id:r.id,going:true})).status,200);assert.equal((await f.call('alice','group','POST',{...g,friends:['charlie']})).status,403);});
test('rotated invitation code invalidates the old code',async()=>{const f=fixture();const old=await f.call('alice','state');await f.call('alice','invite-code','POST',{});assert.equal((await f.call('bob','invite','POST',{code:old.me.code})).status,404);});
test('GPS distance is bounded around reference coordinates',()=>{assert.equal(distance({lat:0,lon:0},{lat:0,lon:0}),0);assert(distance({lat:45,lon:24},{lat:45.001,lon:24})>110);assert(distance({lat:45,lon:24},{lat:45.001,lon:24})<112);});
test('an old phone stopping cannot stop a newer sharing session',async()=>{const f=fixture();const old=await start(f);await f.call('alice','session','DELETE');const fresh=await start(f);assert.equal((await f.call('alice','session?session='+old.id,'DELETE')).status,409);assert.equal((await f.call('alice','state')).me.session.id,fresh.id);});
test('group access closes in both directions after a block',async()=>{const f=fixture();await friends(f);await f.call('alice','group','POST',{name:'Mers',mode:'walk',at:Date.now()+3600000,place:'Parc',lat:45,lon:24,friends:['bob']});await f.call('alice','friend','POST',{id:'bob',action:'block'});assert.equal((await f.call('bob','state')).groups.length,0);assert.equal((await f.call('alice','state')).groups.length,0);});
test('message alarm removes old messages while preserving newer messages',async t=>{const f=fixture();await friends(f);const now=Date.now();await f.call('alice','chat','POST',{friend:'bob',id:randomUUID(),text:'Primul'});t.mock.method(Date,'now',()=>now+3600000);await f.call('alice','chat','POST',{friend:'bob',id:randomUUID(),text:'Al doilea'});t.mock.method(Date,'now',()=>now+7*86400000+10);await f.graph.alarm();const chat=await f.storage.get('chat:alice:bob');assert.equal(chat.length,1);assert.equal(chat[0].text,'Al doilea');});
async function couple(f){await friends(f);assert.equal((await f.call('alice','partner','POST',{id:'bob',action:'invite'})).status,200);assert.equal((await f.call('bob','partner','POST',{id:'alice',action:'accept'})).status,200);}
const continuous=(f,uid='alice',audience='bob')=>f.call(uid,'session','POST',{mode:'partner',minutes:0,continuous:true,audience,consent:true});
const claims=(phone)=>({'x-forja-phone':phone,'x-forja-token-issued':String(Math.floor(Date.now()/1000))});
const phones={alice:'+40721000001',bob:'+40721000002',charlie:'+40721000003'};
const discover=(f,uid)=>f.call(uid,'contacts/discovery','POST',{consent:true},claims(phones[uid]));
const match=(f,uid,numbers)=>f.call(uid,'contacts/match','POST',{numbers,consent:true},claims(phones[uid]));
test('partner association requires mutual accepted friendship and does not start either GPS session',async()=>{const f=fixture();await f.call('bob','state');assert.equal((await continuous(f)).status,403);assert.equal((await f.call('alice','partner','POST',{id:'bob',action:'invite'})).status,403);await friends(f);await f.call('alice','partner','POST',{id:'bob',action:'invite'});assert.equal((await f.call('alice','partner','POST',{id:'bob',action:'accept'})).status,409);assert.equal((await continuous(f)).status,403);await f.call('bob','partner','POST',{id:'alice',action:'accept'});assert.equal((await f.call('alice','state')).me.session,null);assert.equal((await f.call('bob','state')).me.session,null);assert.equal((await continuous(f,'alice','charlie')).status,403);assert.equal((await continuous(f)).status,200);assert.equal((await f.call('bob','state')).me.session,null);});
test('continuous coordinates remain available after 24h only to the selected partner, never other friends',async t=>{const f=fixture();await couple(f);const c=await f.call('charlie','state');await f.call('alice','invite','POST',{code:c.me.code});await f.call('charlie','friend','POST',{id:'alice',action:'accept'});const s=await continuous(f);assert.equal(s.until,0);assert.equal(await f.storage.get('session-expiry:alice'),undefined);const now=Date.now();t.mock.method(Date,'now',()=>now+2*86400000);assert.equal((await f.call('alice','location','POST',fix(s.id))).status,200);assert.equal((await f.call('bob','state')).friends.find(x=>x.id==='alice').location.lat,45);const other=(await f.call('charlie','state')).friends.find(x=>x.id==='alice');assert.equal(other.location,null);assert.equal(other.mode,null);const own=await f.call('alice','state');assert.equal(own.me.explored.length,0);assert.equal(own.me.history.length,0);assert.equal(own.me.session.metres,0);});
test('stale partner coordinates are erased while the voluntary continuous session remains',async t=>{const f=fixture();await couple(f);const s=await continuous(f);const now=Date.now();await f.call('alice','location','POST',fix(s.id));t.mock.method(Date,'now',()=>now+120001);assert.equal((await f.call('bob','state')).friends[0].location,null);await f.graph.alarm();const p=await f.storage.get('user:alice');assert.equal(p.location,null);assert.equal(p.session.id,s.id);});
for(const action of ['disconnect','block','remove'])test(action+' revokes both continuous grants and rejects old phone writes',async()=>{const f=fixture();await couple(f);const a=await continuous(f),b=await continuous(f,'bob','alice');await f.call('alice','location','POST',fix(a.id));await f.call('bob',action==='disconnect'?'partner':'friend','POST',{id:'alice',action});for(const [uid,s]of [['alice',a],['bob',b]]){assert.equal((await f.call(uid,'state')).me.session,null);assert.equal((await f.call(uid,'state')).me.partner,null);assert.equal((await f.call(uid,'location','POST',fix(s.id))).status,409);}assert.equal((await continuous(f)).status,403);});
test('contact discovery requires a fresh verified phone claim and separate consent',async()=>{const f=fixture();assert.equal((await f.call('alice','contacts/discovery','POST',{consent:true})).status,403);assert.equal((await f.call('alice','contacts/discovery','POST',{consent:true,phone:phones.alice})).status,400);assert.equal((await f.call('alice','contacts/discovery','POST',{consent:false},claims(phones.alice))).status,403);assert.equal((await f.call('alice','contacts/discovery','POST',{consent:true},{...claims(phones.alice),'x-forja-token-issued':'1'})).status,401);assert.equal((await discover(f,'alice')).status,200);});
test('matching reveals only opted-in unblocked accounts and never persists raw contact numbers or names',async()=>{const f=fixture();await discover(f,'alice');await discover(f,'bob');await f.call('charlie','state');const r=await match(f,'alice',[phones.alice,phones.bob,phones.charlie]);assert.equal(r.status,200);assert.equal(r.matches.length,1);assert.equal(r.matches[0].index,1);assert.equal(r.matches[0].id,'bob');assert.equal(r.matches[0].friend,false);for(const value of [...f.storage.m.values(),r])for(const phone of Object.values(phones))assert(!JSON.stringify(value).includes(phone));await f.call('bob','friend','POST',{id:'alice',action:'block'});assert.equal((await match(f,'alice',[phones.bob])).matches.length,0);});
test('contact invitations are bound to requester, target and current discoverability; friendship still requires acceptance',async()=>{const f=fixture();for(const uid of Object.keys(phones))await discover(f,uid);const result=await match(f,'alice',[phones.bob]);const m=result.matches[0],body={id:m.id,proof:m.proof};assert.equal((await f.call('charlie','contacts/invite','POST',body,claims(phones.charlie))).status,403);assert.equal((await f.call('alice','contacts/invite','POST',{...body,id:'charlie'},claims(phones.alice))).status,403);assert.equal((await f.call('alice','contacts/invite','POST',body,claims(phones.alice))).status,200);assert.equal((await f.call('alice','state')).friends.length,0);assert.equal((await f.call('bob','state')).incoming[0].id,'alice');await f.call('bob','contacts/discovery','DELETE');assert.equal((await match(f,'alice',[phones.bob])).matches.length,0);assert.equal((await f.call('alice','contacts/invite','POST',body,claims(phones.alice))).status,403);});
test('phone reassignment removes old directory ownership and opt-out does not delete another owner',async()=>{const f=fixture();await discover(f,'alice');await discover(f,'bob');await f.call('charlie','contacts/discovery','POST',{consent:true},claims(phones.bob));assert.equal((await match(f,'alice',[phones.bob])).matches[0].id,'charlie');assert.equal((await match(f,'bob',[phones.alice])).status,403);await f.call('bob','contacts/discovery','DELETE');assert.equal((await match(f,'alice',[phones.bob])).matches[0].id,'charlie');});
test('contact matches enforce format, batch limit and daily quota',async()=>{const f=fixture();await discover(f,'alice');assert.equal((await match(f,'alice',['0721000002'])).status,400);assert.equal((await match(f,'alice',Array(201).fill(phones.bob))).status,400);await f.storage.put('contact-budget:alice',{day:Math.floor(Date.now()/86400000),n:10000});assert.equal((await match(f,'alice',[phones.bob])).status,429);});
test('contact proof expires and inactive directory expires after 30 days',async t=>{const f=fixture();await discover(f,'alice');await discover(f,'bob');const m=(await match(f,'alice',[phones.bob])).matches[0],now=Date.now();t.mock.method(Date,'now',()=>now+600001);assert.equal((await f.call('alice','contacts/invite','POST',{id:m.id,proof:m.proof},claims(phones.alice))).status,403);t.mock.method(Date,'now',()=>now+31*86400000);await f.graph.alarm();assert.equal((await f.call('bob','state')).me.discoverable,false);assert.equal([...f.storage.m.keys()].filter(k=>k.startsWith('phone:')).length,0);});
test('continuous coordinate expiry uses the accepted sample time when phone clock is slightly ahead',async t=>{const f=fixture();await couple(f);const s=await continuous(f),now=Date.now();await f.call('alice','location','POST',fix(s.id,{at:now+5000}));assert.equal(await f.storage.get('expiry:last-position:alice'),now+125000);t.mock.method(Date,'now',()=>now+125001);await f.graph.alarm();assert.equal((await f.storage.get('user:alice')).location,null);});
