package com.forja.app.feature.research;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.nio.file.Files;
import java.nio.file.Path;

/** Compares the production Java transform with binary fixtures generated by official TensorFlow YAMNet. */
public final class SleepSoundClassifierFeaturesTest {
    public static void main(String[] args) throws Exception {
        Path directory = Path.of(args[0]);
        java.util.List<String> names = new java.util.ArrayList<>(java.util.Arrays.asList("silence", "tone440", "white_noise", "tones"));
        if (Files.exists(directory.resolve("snore.pcm"))) names.add("snore");
        for (String name : names) {
            ByteBuffer bytes = ByteBuffer.wrap(Files.readAllBytes(directory.resolve(name + ".pcm"))).order(ByteOrder.LITTLE_ENDIAN);
            float[] wave = new float[bytes.remaining() / 4];
            for (int i = 0; i < wave.length; i++) wave[i] = bytes.getFloat();
            ByteBuffer expected = ByteBuffer.wrap(Files.readAllBytes(directory.resolve(name + ".features"))).order(ByteOrder.LITTLE_ENDIAN);
            float[] actual = SleepSoundClassifier.logMel(wave, 0);
            ByteBuffer output = ByteBuffer.allocate(actual.length * 4).order(ByteOrder.LITTLE_ENDIAN);
            double max = 0;
            for (float value : actual) { max = Math.max(max, Math.abs(value - expected.getFloat())); output.putFloat(value); }
            if (max > 0.002) throw new AssertionError(name + " feature error " + max);
            Files.write(directory.resolve(name + ".java_features"), output.array());
            System.out.println(name + " max_abs_log_mel_error=" + max);
        }
        float[] tail = SleepSoundClassifier.logMel(new float[8000], 0);
        for (float value : tail) if (!Float.isFinite(value)) throw new AssertionError("Nonfinite padded feature");
        try { SleepSoundClassifier.logMel(new float[0], 0); throw new AssertionError("Empty input accepted"); }
        catch (IllegalArgumentException expected) { }
        java.lang.reflect.Method resample = SleepSoundClassifier.class.getDeclaredMethod("resample",
            float[].class, int.class, int.class, SleepSoundClassifier.Cancellation.class);
        resample.setAccessible(true);
        float[] highTone = new float[44100];
        for (int i = 0; i < highTone.length; i++) highTone[i] = (float) (0.5 * Math.sin(2 * Math.PI * 12000 * i / 44100));
        float[] filtered = (float[]) resample.invoke(null, highTone, highTone.length, 44100, null);
        if (filtered.length != 16000) throw new AssertionError("Resampled duration changed");
        double power = 0;
        for (int i = 100; i < filtered.length - 100; i++) power += filtered[i] * filtered[i];
        double rms = Math.sqrt(power / (filtered.length - 200));
        if (rms > 0.005) throw new AssertionError("High-frequency alias was not suppressed: " + rms);
        try {
            resample.invoke(null, highTone, highTone.length, 44100, (SleepSoundClassifier.Cancellation) () -> true);
            throw new AssertionError("Cancelled resampling continued");
        } catch (java.lang.reflect.InvocationTargetException expected) {
            if (!expected.getCause().getClass().getSimpleName().equals("Cancelled")) throw expected;
        }
        System.out.println("12-kHz alias RMS after 44.1-to-16-kHz resampling=" + rms);
        System.out.println("Java YAMNet transform/reference and final-window checks passed");
    }
}
